# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienciapublica',
            name='observacao',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observação'),
        ),
    ]
