# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0002_auto_20180302_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienciapublica',
            name='audiencia_cancelada',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Audiência Cancelada?'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='hora_fim',
            field=models.CharField(max_length=5, verbose_name='Horário Fim(hh:mm)'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='hora_inicio',
            field=models.CharField(max_length=5, verbose_name='Horário Início(hh:mm)'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa', verbose_name='Matéria Legislativa'),
        ),
    ]
