# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0003_auto_20180302_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoaudienciapublica',
            name='tipo',
            field=models.CharField(choices=[('A', 'Audiência Pública'), ('P', 'Plebiscito'), ('R', 'Referendo'), ('I', 'Iniciativa Popular')], default='A', max_length=1, verbose_name='Tipo de Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='audiencia.TipoAudienciaPublica', verbose_name='Tipo de Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='tipoaudienciapublica',
            name='nome',
            field=models.CharField(default='Audiência Pública', max_length=50, verbose_name='Nome do Tipo de Audiência Pública'),
        ),
    ]
