# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0004_auto_20180305_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienciapublica',
            name='hora_fim',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Horário Fim(hh:mm)'),
        ),
    ]
