# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0005_auto_20180806_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienciapublica',
            name='hora_fim',
            field=models.CharField(blank=True, max_length=5, verbose_name='Horário Fim(hh:mm)'),
        ),
    ]
