# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0006_auto_20180808_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoAudienciaPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('assunto', models.TextField(blank=True, verbose_name='Assunto')),
                ('indexacao', models.TextField(blank=True)),
                ('audiencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audiencia.AudienciaPublica')),
            ],
            options={
                'verbose_name': 'Documento Acessório',
                'verbose_name_plural': 'Documentos Acessórios',
            },
        ),
    ]
