# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0007_anexoaudienciapublica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexoaudienciapublica',
            options={'verbose_name': 'Anexo de Documento Acessório', 'verbose_name_plural': 'Anexo de Documentos Acessórios'},
        ),
        migrations.RemoveField(
            model_name='anexoaudienciapublica',
            name='nome',
        ),
        migrations.AlterField(
            model_name='anexoaudienciapublica',
            name='data',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
