# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0008_auto_20181023_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexoaudienciapublica',
            name='indexacao',
        ),
    ]
