# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.audiencia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0010_auto_20190219_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoaudienciapublica',
            name='arquivo',
            field=models.FileField(storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.audiencia.models.anexo_upload_path, verbose_name='Anexo da Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='upload_ata',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.audiencia.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Audiência Pública'),
        ),
        migrations.AlterField(
            model_name='audienciapublica',
            name='upload_pauta',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.audiencia.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Audiência Pública'),
        ),
    ]
