# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0013_auto_20191023_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoaudienciapublica',
            name='arquivo',
            field=models.FileField(max_length=300, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo'),
        ),
    ]
