# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0031_auto_20200407_1406'),
        ('materia', '0067_auto_20200416_1538'),
        ('audiencia', '0014_auto_20191023_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='audienciapublica',
            name='parlamentar_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar Autor'),
        ),
        migrations.AddField(
            model_name='audienciapublica',
            name='requerimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimento', to='materia.MateriaLegislativa', verbose_name='Requerimento da Audiência Pública'),
        ),
    ]
