# Generated by Django 2.2.28 on 2023-05-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiencia', '0017_audienciapublica_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audienciapublica',
            options={'ordering': ['ano', 'numero', 'nome', 'tipo'], 'verbose_name': 'Audiência Pública', 'verbose_name_plural': 'Audiências Públicas'},
        ),
    ]
