# Generated by Django 2.2.28 on 2023-07-31 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoImpressao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificador único da configuração', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]+$', 'Digite apenas letras maiúsculas.')])),
                ('nome', models.CharField(help_text='Nome da configuração de impressão', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da configuração de impressão')),
                ('largura_pagina', models.PositiveIntegerField(default=800, help_text='Largura da página em pixels')),
                ('altura_pagina', models.PositiveIntegerField(default=1200, help_text='Altura da página em pixels')),
                ('margem_superior', models.PositiveIntegerField(default=20, help_text='Margem superior da página em pixels')),
                ('margem_inferior', models.PositiveIntegerField(default=20, help_text='Margem inferior da página em pixels')),
                ('margem_esquerda', models.PositiveIntegerField(default=20, help_text='Margem esquerda da página em pixels')),
                ('margem_direita', models.PositiveIntegerField(default=20, help_text='Margem direita da página em pixels')),
                ('cor_fundo', models.CharField(default='#FFFFFF', help_text='Cor de fundo da página em formato hexadecimal', max_length=7)),
                ('tamanho_fonte', models.PositiveIntegerField(default=12, help_text='Tamanho padrão da fonte em pixels')),
                ('cor_fonte', models.CharField(default='#000000', help_text='Cor padrão da fonte em formato hexadecimal', max_length=7)),
                ('fonte', models.CharField(default='Arial', help_text='Família da fonte utilizada', max_length=100)),
                ('espacamento_linhas', models.PositiveIntegerField(default=1, help_text='Espaçamento entre linhas em pixels')),
            ],
        ),
    ]
