# Generated by Django 2.2.28 on 2023-07-31 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_impressao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='altura_pagina',
            field=models.DecimalField(decimal_places=2, default=1200, help_text='Altura da página em pixels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='identificador',
            field=models.CharField(help_text='Identificador único da configuração', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_-]+$', 'Digite apenas letras maiúsculas, números, underline (_) ou hífen (-).')]),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='largura_pagina',
            field=models.DecimalField(decimal_places=2, default=800, help_text='Largura da página em pixels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='margem_direita',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Margem direita da página em pixels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='margem_esquerda',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Margem esquerda da página em pixels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='margem_inferior',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Margem inferior da página em pixels', max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='margem_superior',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Margem superior da página em pixels', max_digits=6),
        ),
    ]
