# Generated by Django 2.2.28 on 2023-07-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_impressao', '0002_auto_20230731_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoimpressao',
            name='espacamento_linhas',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Espaçamento entre linhas em pixels', max_digits=6),
        ),
    ]
