sapldb:
  image: postgres:10.5-alpine
  restart: always
  environment:
    POSTGRES_PASSWORD: sapl
    POSTGRES_USER: sapl
    POSTGRES_DB: sapl
    PGDATA : /var/lib/postgresql/data/
  volumes:
    - sapldb_data:/var/lib/postgresql/data/
  ports:
    - "5435:5432"
saplredis:
  image: redis:5.0.3-stretch
  restart: always
  ports:
    - "6379:6379"
sapl:
  #image: interlegis/sapl:master
  build: .
  dockerfile: Dockerfile.dev
  restart: always
  environment:
    ADMIN_PASSWORD: interlegis
    ADMIN_EMAIL: email@dominio.net
    DEBUG: 'True'
    EMAIL_PORT: 587
    EMAIL_USE_TLS: 'False'
    EMAIL_HOST: smtp.dominio.net
    EMAIL_HOST_USER: usuariosmtp
    EMAIL_SEND_USER: usuariosmtp
    EMAIL_HOST_PASSWORD: senhasmtp
    USE_CHANNEL_LAYERS: 'True'
    PORT_CHANNEL_LAYERS: 6379
    HOST_CHANNEL_LAYERS: saplredis
    TZ: America/Sao_Paulo
  volumes:
    - ./sapl:/var/interlegis/sapl/sapl
  links:
    - sapldb
    - saplredis
  ports:
    - "80:80"
