# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0002_auto_20170504_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='data_inicio_mandato',
            field=models.DateField(default=datetime.datetime(2017, 7, 7, 16, 56, 58, 525896), verbose_name='Início do Mandato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data_fim_mandato',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Mandato'),
        ),
    ]
