# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0003_auto_20170707_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='data_inicio_mandato',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Mandato'),
        ),
    ]
