# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0008_adiciona_cargos_mesa'),
        ('parlamentares', '0006_auto_20170905_0833'),
    ]

    operations = [
    ]
