# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-05 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0008_adiciona_cargos_mesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacaomilitar',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo Situação Militar', 'verbose_name_plural': 'Tipos Situações Militares'},
        ),
        migrations.AlterModelOptions(
            name='tipoafastamento',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Afastamento', 'verbose_name_plural': 'Tipos de Afastamento'},
        ),
        migrations.AlterModelOptions(
            name='tipodependente',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Dependente', 'verbose_name_plural': 'Tipos de Dependente'},
        ),
    ]
