# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-10 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0010_corrige_data_inicio_mandato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='data_inicio_mandato',
            field=models.DateField(null=True, verbose_name='Início do Mandato'),
        ),
    ]
