# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-20 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0011_auto_20171010_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipodependente',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='Descrição'),
        ),
    ]
