# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-30 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0012_auto_20171020_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelinstrucao',
            options={'ordering': ['descricao'], 'verbose_name': 'Nível Instrução', 'verbose_name_plural': 'Níveis Instrução'},
        ),
    ]
