# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='unidade_deliberativa',
            field=models.BooleanField(default=False, verbose_name='Unidade Deliberativa'),
        ),
    ]
