# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0014_auto_20160318_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='data_expedicao_diploma',
            field=models.DateField(verbose_name='Expedição do Diploma'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='data_fim_mandato',
            field=models.DateField(verbose_name='Fim do Mandato'),
        ),
    ]
