# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0014_auto_20180131_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlamentar',
            name='municipio_residencia_old',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
