# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0015_auto_20160322_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=sapl.parlamentares.models.foto_upload_path, validators=[
                                    sapl.utils.restringe_tipos_de_arquivo_img], verbose_name='Fotografia'),
        ),
    ]
