# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-15 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0017_auto_20180202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='data_expedicao_diploma',
            field=models.DateField(blank=True, null=True, verbose_name='Expedição do Diploma'),
        ),
    ]
