# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0018_auto_20180215_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Parlamentar'),
        ),
    ]
