# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.parlamentares.models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0021_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaolegislativa',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Legislatura', verbose_name=sapl.parlamentares.models.Legislatura),
        ),
    ]
