# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 17:48
from __future__ import unicode_literals
from django.db import migrations
from django.core.management import call_command
import json
import os



def gera_partidos_tse(apps, schema_editor):
    Partido = apps.get_model("parlamentares", "Partido")
    db_alias = schema_editor.connection.alias
    partidos = Partido.objects.all().exists()

    if partidos:
        # Caso haja algum partido cadastrado na base de dados,
        # a migração não deve ser carregada para evitar duplicações de dados.
        print("Carga de Partido não efetuada. Já Existem partidos cadastrados...")
    else:
        fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
        # pega partidos listados em fixtures/pre_popula_partidos.json
        fixture_filename = 'pre_popula_partidos.json'
        fixture_file = os.path.join(fixture_dir, fixture_filename)
        call_command('loaddata', fixture_file, ignorenonexistent=True)

class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0022_partido_observacao'),
    ]

    operations = [
        migrations.RunPython(gera_partidos_tse),
    ]

