# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0022_auto_20160702_1519'),
        ('parlamentares', '0023_auto_20160628_1247'),
    ]

    operations = [
    ]
