# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0023_auto_20180626_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='titular',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], db_index=True, default=True, verbose_name='Parlamentar Titular'),
        ),
    ]
