# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0024_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='ativo',
            field=models.BooleanField(db_index=True, verbose_name='Ativo na Casa?'),
        ),
    ]
