# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0024_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da Frente')),
                ('data_criacao', models.DateField(verbose_name='Data Criação')),
                ('data_extincao', models.DateField(blank=True, verbose_name='Data Dissolução')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('parlamentares', models.ManyToManyField(blank=True, to='parlamentares.Parlamentar', verbose_name='Parlamentares')),
            ],
            options={
                'verbose_name': 'Frente',
                'verbose_name_plural': 'Frentes',
            },
        ),
    ]
