# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0025_auto_20180924_1724'),
        ('sessao', '0039_auto_20190430_0825')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome do Bloco')),
                ('data_criacao', models.DateField(null=True, verbose_name='Data Criação')),
                ('data_extincao', models.DateField(blank=True, null=True, verbose_name='Data Dissolução')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('partidos', models.ManyToManyField(blank=True, to='parlamentares.Partido', verbose_name='Partidos')),
            ],
            options={
                'db_table': 'parlamentares_bloco',
                'verbose_name': 'Bloco Parlamentar',
                'verbose_name_plural': 'Blocos Parlamentares',
            },
            bases=(models.Model,),
        ),
        migrations.AlterField(
            model_name='composicaocoligacao',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Partido', verbose_name='Partidos da Coligação'),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
