# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0025_auto_20180924_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='historico',
            field=models.TextField(blank=True, verbose_name='Histórico'),
        ),
    ]
