# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0025_auto_20180924_1724'),
    ]

    operations = [
    ]
