# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0026_bloco'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloco',
            table=None,
        ),
    ]
