# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0026_auto_20160916_1034'),
        ('parlamentares', '0025_auto_20160916_1030'),
    ]

    operations = [
    ]
