# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0027_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoafastamento',
            name='afastamento',
        ),
        migrations.RemoveField(
            model_name='tipoafastamento',
            name='fim_mandato',
        ),
        migrations.AddField(
            model_name='tipoafastamento',
            name='indicador',
            field=models.CharField(choices=[('A', 'Afastamento'), ('F', 'Fim de Mandato')], default='F', max_length=1, verbose_name='Indicador'),
        ),
    ]
