# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0027_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislatura',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
