# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0027_auto_20190313_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=9, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_alteracao', models.DateField(default=django.utils.timezone.now, verbose_name='Data Alteração')),
            ],
        ),
        migrations.AddField(
            model_name='historicopartido',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Partido'),
        ),
    ]
