# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0028_auto_20190515_1744'),
    ]

    operations = [
        migrations.RunSQL("""
            update django_content_type set 
                app_label = 'parlamentares',
                model = 'bloco'
            where app_label = 'sessao' and model = 'bloco'
        """),
    ]
