# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0028_auto_20190403_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopartido',
            name='proximo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.HistoricoPartido'),
        ),
    ]
