# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0028_auto_20160922_1443'),
        ('parlamentares', '0028_legislatura_numero'),
    ]

    operations = [
    ]
