# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0029_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodependente',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
