# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0029_auto_20190517_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=9, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('inicio_historico', models.DateField(verbose_name='Data Alteração')),
                ('fim_historico', models.DateField(verbose_name='Data Alteração')),
                ('logo_partido', models.ImageField(blank=True, null=True, upload_to=sapl.parlamentares.models.logo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_img], verbose_name='Logo Partido')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Partido')),
            ],
        ),
        migrations.AlterModelTable(
            name='bloco',
            table=None,
        ),
    ]
