# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0030_auto_20190409_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicopartido',
            name='proximo',
        ),
        migrations.AlterField(
            model_name='composicaocoligacao',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Partido', verbose_name='Partidos da Coligação'),
        ),
    ]
