# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0030_auto_20160928_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaolegislativa',
            options={'ordering': ['-data_inicio', '-data_fim'], 'verbose_name': 'Sessão Legislativa', 'verbose_name_plural': 'Sessões Legislativas'},
        ),
    ]
