# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-07 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0030_auto_20190613_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='sigla',
            field=models.CharField(max_length=20, verbose_name='Sigla'),
        ),
    ]
