# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0031_auto_20190411_0919'),
        ('parlamentares', '0027_auto_20190430_0839'),
    ]

    operations = [
    ]
