# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0031_parlamentar_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlamentar',
            name='autor',
        ),
    ]
