# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0031_auto_20190520_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargomembrobancada',
            options={'verbose_name': 'Cargo de Bancada', 'verbose_name_plural': 'Cargos de Bancada'},
        ),
        migrations.AlterModelTable(
            name='cargobancada',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cargomembrobancada',
            table='parlamentares_cargobancada',
        ),
    ]
