# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0031_auto_20160929_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenteProxyMasterDetail',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('parlamentares.frente',),
        ),
    ]
