# Generated by Django 2.2.13 on 2020-10-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0032_frente_parlamentar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mandato',
            options={'ordering': ('id',), 'verbose_name': 'Mandato', 'verbose_name_plural': 'Mandatos'},
        ),
    ]
