# Generated by Django 2.2.13 on 2020-10-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0032_frente_parlamentar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'ordering': ('partidos__nome', 'nome'), 'verbose_name': 'Bloco Parlamentar', 'verbose_name_plural': 'Blocos Parlamentares'},
        ),
        migrations.AlterModelOptions(
            name='cargomesa',
            options={'ordering': ('unico', 'descricao'), 'verbose_name': 'Cargo na Mesa', 'verbose_name_plural': 'Cargos na Mesa'},
        ),
        migrations.AlterModelOptions(
            name='coligacao',
            options={'ordering': ('legislatura', 'nome'), 'verbose_name': 'Coligação', 'verbose_name_plural': 'Coligações'},
        ),
        migrations.AlterModelOptions(
            name='composicaocoligacao',
            options={'ordering': ('partido',), 'verbose_name': 'Composição Coligação', 'verbose_name_plural': 'Composição Coligações'},
        ),
        migrations.AlterModelOptions(
            name='composicaomesa',
            options={'ordering': ('cargo', '-sessao_legislativa', 'parlamentar'), 'verbose_name': 'Ocupação de cargo na Mesa', 'verbose_name_plural': 'Ocupações de cargo na Mesa'},
        ),
        migrations.AlterModelOptions(
            name='dependente',
            options={'ordering': ('parlamentar', 'nome'), 'verbose_name': 'Dependente', 'verbose_name_plural': 'Dependentes'},
        ),
        migrations.AlterModelOptions(
            name='frente',
            options={'ordering': ('nome', '-data_criacao'), 'verbose_name': 'Frente Parlamentar', 'verbose_name_plural': 'Frentes Parlamentares'},
        ),
        migrations.AlterModelOptions(
            name='legislatura',
            options={'ordering': ('-numero', '-data_inicio', '-data_fim'), 'verbose_name': 'Legislatura', 'verbose_name_plural': 'Legislaturas'},
        ),
        migrations.AlterModelOptions(
            name='mandato',
            options={'ordering': ('parlamentar', 'legislatura__numero'), 'verbose_name': 'Mandato', 'verbose_name_plural': 'Mandatos'},
        ),
        migrations.AlterModelOptions(
            name='votante',
            options={'ordering': ('parlamentar', '-data'), 'permissions': (('can_vote', 'Can Vote'),), 'verbose_name': 'Usuário Votante', 'verbose_name_plural': 'Usuários Votantes'},
        ),
    ]
