# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0032_merge_20190507_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopartido',
            name='fim_historico',
            field=models.DateField(verbose_name='Data Alteração'),
        ),
        migrations.AlterField(
            model_name='historicopartido',
            name='inicio_historico',
            field=models.DateField(verbose_name='Data Alteração'),
        ),
    ]
