# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0033_afastamentoparlamentar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandato',
            name='tipo_afastamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.TipoAfastamento', verbose_name='Tipo de Afastamento'),
        ),
    ]
