# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 15:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('parlamentares', '0033_auto_20190712_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoMembroBancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início do Membro no Cargo')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim do Membro no Cargo')),
            ],
            options={
                'verbose_name': 'Cargo Membro Bancada Parlamentar',
                'verbose_name_plural': 'Cargos Membros Bancada Parlamentar',
                'ordering': ('-data_inicio',),
            },
        ),
        migrations.CreateModel(
            name='MembroBancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início de Membro')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim de Membro')),
            ],
            options={
                'verbose_name': 'Membro Bancada Parlamentar',
                'verbose_name_plural': 'Membros Bancada Parlamentar',
                'ordering': ('parlamentar', '-data_inicio',),
            },
        ),
        migrations.AlterModelOptions(
            name='bancada',
            options={'ordering': ('nome',), 'verbose_name': 'Bancada Parlamentar',
                     'verbose_name_plural': 'Bancadas Parlamentares'},
        ),
        migrations.AlterModelOptions(
            name='cargobancada',
            options={'ordering': ('nome_cargo',), 'verbose_name': 'Cargo Bancada Parlamentar',
                     'verbose_name_plural': 'Cargos Bancada Parlamentar'},
        ),
        migrations.RemoveField(
            model_name='bancada',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='bancada',
            name='data_extincao',
        ),
        migrations.RemoveField(
            model_name='bancada',
            name='legislatura',
        ),
        migrations.RemoveField(
            model_name='bancada',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='cargobancada',
            name='cargo_unico',
        ),
        migrations.AddField(
            model_name='bancada',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], db_index=True, default=True,
                                      verbose_name='Bancada Parlamentar ativa?'),
        ),
        migrations.AddField(
            model_name='cargobancada',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bancada',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome da Bancada Parlamentar'),
        ),
        migrations.AlterField(
            model_name='cargobancada',
            name='nome_cargo',
            field=models.CharField(max_length=30, verbose_name='Nome do Cargo'),
        ),
        migrations.AlterModelTable(
            name='cargobancada',
            table=None,
        ),
        migrations.AddField(
            model_name='membrobancada',
            name='bancada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Bancada',
                                    verbose_name='Bancada Parlamentar'),
        ),
        migrations.AddField(
            model_name='membrobancada',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Legislatura',
                                    verbose_name='Legislatura do Membro'),
        ),
        migrations.AddField(
            model_name='membrobancada',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Parlamentar',
                                    verbose_name='Parlamentar'),
        ),
        migrations.AddField(
            model_name='cargomembrobancada',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.CargoBancada',
                                    verbose_name='Cargo do Membro'),
        ),
        migrations.AddField(
            model_name='cargomembrobancada',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.MembroBancada',
                                    verbose_name='Membro no Cargo'),
        ),
        migrations.AlterModelOptions(
            name='cargobancada',
            options={'ordering': ('nome',), 'verbose_name': 'Cargo Bancada Parlamentar',
                     'verbose_name_plural': 'Cargos Bancada Parlamentar'},
        ),
        migrations.RenameField(
            model_name='cargobancada',
            old_name='nome_cargo',
            new_name='nome',
        ),
    ]
