# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0033_auto_20190712_1132'),
        ('parlamentares', '0034_auto_20190801_1408'),
    ]

    operations = [
    ]
