# Generated by Django 2.2.13 on 2021-03-15 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remove_grupo_votante_de_usuario(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')

    g = Group.objects.get(name='Votante')

    # usuários do grupo votante sem vínculo com parlamentar
    users_votantes = g.user_set.filter(votante_set__isnull=True)
    for u in users_votantes:
        u.groups.remove(g)


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0034_auto_20210303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votante',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='votante_set', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='votante_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),

        migrations.RunPython(remove_grupo_votante_de_usuario),


    ]
