# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models

def aloca_datas(apps, schema_editor):
    ComposicaoMesa = apps.get_model("parlamentares", "ComposicaoMesa")
    db_alias = schema_editor.connection.alias
    composicao_mesa = ComposicaoMesa.objects.all()

    for c in composicao_mesa:
        c.data_inicio = c.sessao_legislativa.data_inicio
        c.data_fim = c.sessao_legislativa.data_fim
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0035_merge_20190802_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaomesa',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim'),
        ),
        migrations.AddField(
            model_name='composicaomesa',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início'),
        ),
        migrations.RunPython(aloca_datas),
        migrations.AlterField(
            model_name='composicaomesa',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Início'),
        ),
    ]
