# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0035_auto_20161011_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='logo_partido',
            field=models.ImageField(blank=True, null=True, upload_to=sapl.parlamentares.models.logo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_img], verbose_name='Logo Partido'),
        ),
    ]
