# Generated by Django 2.2.20 on 2021-07-06 19:24

from django.db import migrations, models
import django.db.models.deletion
import sapl.parlamentares.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0035_auto_20210315_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReuniaoFrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Reunião')),
                ('tema', models.CharField(blank=True, max_length=150, verbose_name='Tema da Reunião')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(null=True, verbose_name='Horário de Início (hh:mm)')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Término (hh:mm)')),
                ('local_reuniao', models.CharField(blank=True, max_length=100, verbose_name='Local da Reunião')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('url_audio', models.URLField(blank=True, max_length=150, verbose_name='URL do Arquivo de Áudio (Formatos MP3 / AAC)')),
                ('url_video', models.URLField(blank=True, max_length=150, verbose_name='URL do Arquivo de Vídeo (Formatos MP4 / FLV / WebM)')),
                ('upload_pauta', models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.parlamentares.models.pauta_upload_path, verbose_name='Pauta da Reunião')),
                ('upload_ata', models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.parlamentares.models.ata_upload_path, verbose_name='Ata da Reunião')),
                ('upload_anexo', models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.parlamentares.models.anexo_upload_path, verbose_name='Anexo da Reunião')),
                ('frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Frente', verbose_name='Frente Parlamentar')),
            ],
            options={
                'verbose_name': 'Reunião de Frente Parlamentar',
                'verbose_name_plural': 'Reuniões de Frentes Parlamentares',
                'ordering': ('numero', 'frente'),
            },
        ),
    ]
