# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0036_parlamentarfrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=80, verbose_name='Cargo de Frente Parlamentar')),
                ('cargo_unico', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Cargo Único ?')),
            ],
            options={
                'verbose_name': 'Cargo de Frente Parlamentar',
                'ordering': ('nome_cargo',),
                'verbose_name_plural': 'Cargos de Frente Parlamentar',
            },
        ),
        migrations.AlterField(
            model_name='parlamentarfrente',
            name='frente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Frente', verbose_name='Frente'),
        ),
        migrations.AlterField(
            model_name='parlamentarfrente',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
