# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0037_votante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'verbose_name': 'Usuários'},
        ),
    ]
