# Generated by Django 2.2.20 on 2021-07-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0037_atribuiMesaDiretora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicaomesa',
            name='sessao_legislativa',
        ),
    ]
