# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0037_auto_20191025_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parlamentarfrente',
            options={'ordering': ('cargo',), 'verbose_name': 'Parlamentar', 'verbose_name_plural': 'Parlamentares'},
        ),
        migrations.AddField(
            model_name='parlamentarfrente',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.CargoFrente', verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
