# Generated by Django 2.2.20 on 2022-07-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0038_sessao_legislativa_redundante'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislatura',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
