# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0038_auto_20170213_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votante',
            name='ip',
        ),
    ]
