# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 15:05
from __future__ import unicode_literals

from django.db import migrations
from datetime import date

def popula_cargoFrente_inicial(apps, schema_editor):
    CargoFrente = apps.get_model('parlamentares', 'CargoFrente')

    cargoFrenteMembro = CargoFrente()
    cargoFrenteMembro.nome_cargo = 'Membro'
    cargoFrenteMembro.cargo_unico = False
    cargoFrenteMembro.save()

    cargoFrentePresidente = CargoFrente()
    cargoFrentePresidente.nome_cargo = 'Presidente'
    cargoFrentePresidente.cargo_unico = True
    cargoFrentePresidente.save()

class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0038_auto_20191025_1142'),
    ]

    operations = [
        migrations.RunPython(popula_cargoFrente_inicial)
    ]
