# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-14 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0039_remove_votante_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votante',
            options={'permissions': (('can_vote', 'Can Vote'),), 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
