# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 15:05
from __future__ import unicode_literals

from django.db import migrations
from datetime import date

def transfere_parlamentar_frente(apps, schema_editor):
    Frente = apps.get_model('parlamentares', 'Frente')
    ParlamentarFrente = apps.get_model('parlamentares', 'ParlamentarFrente')
    CargoFrente = apps.get_model('parlamentares', 'CargoFrente')
    for frente in Frente.objects.all():
        for parlamentar in frente.parlamentares.all():
            parlamentarFrente = ParlamentarFrente()
            parlamentarFrente.frente = frente
            parlamentarFrente.parlamentar = parlamentar
            parlamentarFrente.cargo = CargoFrente.objects.first()
            parlamentarFrente.data_entrada = date.today()
            parlamentarFrente.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0039_popula_CargoFrente'),
    ]

    operations = [
        migrations.RunPython(transfere_parlamentar_frente)
    ]
