# Generated by Django 2.2.28 on 2022-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0039_legislatura_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='rg',
            field=models.CharField(blank=True, max_length=20, verbose_name='R.G.'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=25, verbose_name='Título de Eleitor'),
        ),
    ]
