# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0040_auto_20170214_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandato',
            name='titular',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], db_index=True, default=False, verbose_name='Vereador Titular ?'),
        ),
    ]
