# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0040_transfere_parlamentar_frente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frente',
            name='parlamentares',
        ),
    ]
