# Generated by Django 2.2.28 on 2023-01-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0040_auto_20220806_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlamentar',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=50, verbose_name='Celular'),
        ),
    ]
