# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0041_remove_frente_parlamentares'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParlamentarBancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data Entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data Saída')),
                ('bancada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Bancada', verbose_name='Bancada')),
            ],
            options={
                'verbose_name_plural': 'Parlamentares',
                'verbose_name': 'Parlamentar',
                'ordering': ('cargo',),
            },
        ),
        migrations.AlterModelOptions(
            name='cargobancada',
            options={'ordering': ('nome_cargo',), 'verbose_name': 'Cargo de Bancada', 'verbose_name_plural': 'Cargos de Bancada'},
        ),
        migrations.AddField(
            model_name='parlamentarbancada',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.CargoBancada', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='parlamentarbancada',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
