# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0041_mandato_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coligacao',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.AlterField(
            model_name='composicaocoligacao',
            name='coligacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Coligacao'),
        ),
        migrations.AlterField(
            model_name='composicaocoligacao',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Partido', verbose_name='Partidos da Coligação'),
        ),
        migrations.AlterField(
            model_name='composicaomesa',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.CargoMesa'),
        ),
        migrations.AlterField(
            model_name='composicaomesa',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='composicaomesa',
            name='sessao_legislativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.SessaoLegislativa'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.TipoDependente', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Partido', verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='coligacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Coligacao', verbose_name='Coligação'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='tipo_afastamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.TipoAfastamento'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='municipio_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='nivel_instrucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.NivelInstrucao', verbose_name='Nível Instrução'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='situacao_militar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.SituacaoMilitar', verbose_name='Situação Militar'),
        ),
        migrations.AlterField(
            model_name='sessaolegislativa',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parlamentar', to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='votante',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
