# Generated by Django 2.2.28 on 2023-10-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0042_auto_20230529_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargomesa',
            options={'ordering': ['id_ordenacao', 'unico', 'descricao'], 'verbose_name': 'Cargo na Mesa', 'verbose_name_plural': 'Cargos na Mesa'},
        ),
        migrations.AddField(
            model_name='cargomesa',
            name='id_ordenacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Posição na Ordenação'),
        ),
    ]
