# Generated by Django 2.2.28 on 2025-12-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0044_adiciona_cargos_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='nome_completo',
            field=models.CharField(max_length=80, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='parlamentar',
            name='nome_parlamentar',
            field=models.CharField(max_length=80, verbose_name='Nome Parlamentar'),
        ),
    ]
