# Generated by Django 2.2.28 on 2026-04-13 01:48

from django.db import migrations, models
import django.db.models.deletion
from datetime import date

def add_legislatura_to_mesa_diretora(apps, schema_editor):
    MesaDiretora = apps.get_model('parlamentares', 'MesaDiretora')
    SessaoLegislativa = apps.get_model('parlamentares', 'SessaoLegislativa')

    for mesa in MesaDiretora.objects.all():
        mesa.legislatura = mesa.sessao_legislativa.legislatura
        data_inicio = mesa.sessao_legislativa.data_inicio
        data_fim = mesa.sessao_legislativa.data_fim
        if data_inicio.year == data_fim.year:
            mesa.data_inicio = date(data_inicio.year, 1, 1)
            mesa.data_fim = date(data_fim.year, 12, 31)
        else:
            mesa.data_inicio = data_inicio
            mesa.data_fim = data_fim
        mesa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0045_auto_20251201_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesadiretora',
            name='legislatura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.RunPython(add_legislatura_to_mesa_diretora),
    ]
