# Generated by Django 2.2.28 on 2026-04-13 01:48

from django.db import migrations, models
import django.db.models.deletion
from datetime import date

def add_legislatura_to_mesa_diretora(apps, schema_editor):
    schema_editor.execute("""
        UPDATE parlamentares_mesadiretora md
        SET
            legislatura_id = sl.legislatura_id,
            data_inicio = sl.data_inicio,
            data_fim = sl.data_fim
        FROM
            parlamentares_sessaolegislativa sl
        WHERE
            sl.id = md.sessao_legislativa_id
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0045_auto_20251201_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesadiretora',
            name='legislatura',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.RunPython(add_legislatura_to_mesa_diretora),
    ]
