# Generated by Django 2.2.28 on 2026-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0045_auto_20251201_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlamentar',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Última Atualização'),
        ),
    ]
