# Generated by Django 2.2.28 on 2026-04-13 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0046_mesadiretora_legislatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesadiretora',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.RemoveField(
            model_name='mesadiretora',
            name='sessao_legislativa',
        ),
    ]
