# Generated by Django 2.2.28 on 2026-04-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0048_auto_20260413_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicaomesa',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.CargoMesa', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='composicaomesa',
            name='mesa_diretora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicaomesa_set', to='parlamentares.MesaDiretora', verbose_name='Mesa Diretora'),
        ),
        migrations.AlterField(
            model_name='composicaomesa',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='mesadiretora',
            name='data_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='mesadiretora',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Início'),
        ),
    ]
