# Generated by Django 2.2.28 on 2026-04-18 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0049_auto_20260417_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesadiretora',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesadiretora_set', to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
    ]
