# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argumento', models.CharField(max_length=50, verbose_name='Argumento')),
            ],
            options={
                'verbose_name': 'Argumento da constraint',
                'verbose_name_plural': 'Argumentos da constraint',
            },
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tabela', models.CharField(max_length=50, verbose_name='Nome da tabela')),
                ('nome_constraint', models.CharField(max_length=100, verbose_name='Nome da constraint')),
                ('nome_model', models.CharField(max_length=50, verbose_name='Nome da model')),
                ('tipo_constraint', models.CharField(max_length=50, verbose_name='Tipo da constraint')),
            ],
            options={
                'verbose_name': 'Constraint removida',
                'verbose_name_plural': 'Constraints removidas',
            },
        ),
        migrations.AddField(
            model_name='problemamigracao',
            name='eh_importante',
            field=models.BooleanField(default=False, verbose_name='É importante?'),
        ),
        migrations.AddField(
            model_name='argumento',
            name='constraint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Constraint'),
        ),
    ]
