# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170519_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='num_inicial_sequencia',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número inicial Sequência'),
        ),
    ]
