# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170519_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemamigracao',
            name='eh_importante',
        ),
        migrations.AddField(
            model_name='problemamigracao',
            name='critico',
            field=models.BooleanField(default=False, verbose_name='Crítico'),
        ),
    ]
