# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-02 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170714_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo'),
        ),
    ]
