# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-08-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20170802_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
