# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170802_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ('nome',), 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
