# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170808_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='sequencia_numeracao',
            field=models.CharField(choices=[('A', 'Sequencial por ano'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], default='A', max_length=1, verbose_name='Sequência de numeração'),
        ),
    ]
