# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-09 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20170808_0850'),
        ('base', '0007_auto_20170808_1713'),
    ]

    operations = [
    ]
