# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170814_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='mostrar_brasao_painel',
            field=models.BooleanField(default=False, verbose_name='Mostrar brasão da Casa no painel?'),
        ),
    ]
