# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_appconfig_mostrar_brasao_painel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='painel_aberto',
        ),
    ]
