# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20171121_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoautor',
            name='descricao',
            field=models.CharField(help_text='Obs: Não crie tipos de autores semelhante aos tipos fixos. ', max_length=50, verbose_name='Descrição'),
        ),
    ]
