# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_problemamigracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemamigracao',
            name='eh_stub',
            field=models.BooleanField(default=False, verbose_name='É stub?'),
            preserve_default=False,
        ),
    ]
