# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_problemamigracao_eh_stub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemamigracao',
            name='endereco',
        ),
    ]
