# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20180201_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='logotipo',
            field=models.ImageField(blank=True, upload_to='sapl/public/casa/logotipo/', verbose_name='Logotipo'),
        ),
    ]
