# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160502_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemamigracao',
            name='nome_campo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do(s) Campo(s)'),
        ),
    ]
