# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-23 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20180219_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='receber_recibo_proposicao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Protocolar proposição somente com recibo?'),
        ),
    ]
