# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-26 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_appconfig_receber_recibo_proposicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumento',
            name='constraint',
        ),
        migrations.RemoveField(
            model_name='problemamigracao',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Argumento',
        ),
        migrations.DeleteModel(
            name='Constraint',
        ),
        migrations.DeleteModel(
            name='ProblemaMigracao',
        ),
    ]
