# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_problemamigracao_nome_campo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casalegislativa',
            options={'verbose_name': 'Casa Legislativa', 'verbose_name_plural': 'Casa Legislativa'},
        ),
    ]
