# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-23 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20180326_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_consideracoes',
            field=models.TimeField(blank=True, null=True, verbose_name='Cronômetro de Considerações Finais'),
        ),
    ]
