# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20160701_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='casalegislativa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'Assembleia Legislativa'), ('C', 'Casa Legislativa')], max_length=1, verbose_name='Tipo'),
        ),
    ]
