# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_appconfig_cronometro_consideracoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nome do Autor'),
        ),
    ]
