# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_appconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'verbose_name': 'Configurações da Aplicação', 'verbose_name_plural': 'Configurações da Aplicação'},
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='documentos_administrativos',
            field=models.CharField(choices=[('O', 'Ostensivo'), ('R', 'Restritivo')], default='O', max_length=1, verbose_name='Ostensivo/Restritivo'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='painel_aberto',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Painel aberto para usuário anônimo'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sequencia_numeracao',
            field=models.CharField(choices=[('A', 'Sequencial por ano'), ('U', 'Sequencial único')], default='A', max_length=1, verbose_name='Sequência de numeração'),
        ),
    ]
