# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160919_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='tipo',
            field=models.CharField(choices=[('A', 'Assembleia Legislativa'), ('C', 'Casa Legislativa')], default='C', max_length=1, verbose_name='Tipo'),
        ),
    ]
