# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20160928_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='texto_articulado_materia',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Usar Textos Articulados para Matérias'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='texto_articulado_norma',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Usar Textos Articulados para Normas'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='texto_articulado_proposicao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Usar Textos Articulados para Proposições'),
        ),
    ]
