# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160919_1333'),
        ('base', '0019_auto_20160919_1040'),
    ]

    operations = [
    ]
