# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20180815_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='documentos_administrativos',
            field=models.CharField(choices=[('O', 'Ostensiva'), ('R', 'Restritiva')], default='O', max_length=1, verbose_name='Visibilidade dos Documentos Administrativos'),
        ),
    ]
