# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20180821_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressaoTextual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bind', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Expressão encontrada no SAPL')),
                ('value', models.CharField(max_length=10000, unique=True, verbose_name='Expressão Oficial')),
                ('custom', models.CharField(blank=True, default='', max_length=10000, verbose_name='Expressão Customizada')),
            ],
            options={
                'verbose_name': 'Expressão Textual do SAPL',
                'verbose_name_plural': 'Expressões Textuais do SAPL',
                'ordering': ('value',),
            },
        ),
        migrations.AlterField(
            model_name='casalegislativa',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código'),
        ),
    ]
