# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_appconfig_esfera_federacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='assinatura_ata',
            field=models.CharField(choices=[('M', 'Mesa do dia'), ('P', 'Apenas o presidente do dia'), ('T', 'Todos os presentes')], default='T', max_length=1, verbose_name='Quem deve assina a ata'),
        ),
    ]
