# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-25 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20180825_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressaotextual',
            name='custom',
            field=models.TextField(blank=True, default='', verbose_name='Expressão Customizada'),
        ),
        migrations.AlterField(
            model_name='expressaotextual',
            name='value',
            field=models.TextField(unique=True, verbose_name='Expressão Oficial'),
        ),
    ]
