# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20161009_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoautor',
            name='content_type',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Modelagem no SAPL'),
        ),
        migrations.AlterUniqueTogether(
            name='autor',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
