# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_appconfig_assinatura_ata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='assinatura_ata',
            field=models.CharField(choices=[('M', 'Mesa Diretora da Sessão'), ('P', 'Apenas o Presidente da Sessão'), ('T', 'Todos os Parlamentares Presentes na Sessão')], default='T', max_length=1, verbose_name='Quem deve assina a ata'),
        ),
    ]
