# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20181105_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='cronometro_aparte',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro do Aparte'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='cronometro_consideracoes',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro de Considerações Finais'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='cronometro_discurso',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro do Discurso'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='cronometro_ordem',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro da Ordem'),
        ),
    ]
