# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_tipoautor_cria_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoautor',
            name='cria_usuario',
        ),
    ]
