# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20161011_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='proposicao_incorporacao_obrigatoria',
            field=models.BooleanField(choices=[('O', 'Sempre Gerar Protocolo.'), ('C', 'Perguntar se é pra gerar protocolo ao incorporar.'), ('N', 'Nunca Protocolar ao incorporar uma proposição.')], default='O', verbose_name='Regra de incorporação e protocolo'),
        ),
    ]
