# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_appconfig_relatorios_atos'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='estatisticas_acesso_normas',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Estatísticas de acesso a normas'),
        ),
    ]
