# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-18 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_appconfig_estatisticas_acesso_normas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='relatorios_atos',
        ),
    ]
