# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20161021_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='proposicao_incorporacao_obrigatoria',
            field=models.CharField(choices=[('O', 'Sempre Gerar Protocolo'), ('C', 'Perguntar se é pra gerar protocolo ao incorporar'), ('N', 'Nunca Protocolar ao incorporar uma proposição')], default='O', max_length=1, verbose_name='Regra de incorporação de proposições e protocolo'),
        ),
    ]
