# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20161021_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoautor',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Autor', 'verbose_name_plural': 'Tipos de Autor'},
        ),
    ]
