# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20170203_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_aparte',
            field=models.TimeField(blank=True, null=True, verbose_name='Cronômetro do Aparte'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_discurso',
            field=models.TimeField(blank=True, null=True, verbose_name='Cronômetro do Discurso'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_ordem',
            field=models.TimeField(blank=True, null=True, verbose_name='Cronômetro da Ordem'),
        ),
    ]
