# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20190218_1109'),
        ('base', '0030_appconfig_escolher_numero_materia_proposicao'),
    ]

    operations = [
    ]
