# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20190415_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='sequencia_numeracao',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='sequencia_numeracao_proposicao',
            field=models.CharField(choices=[('A', 'Sequencial por ano para cada autor'), ('B', 'Sequencial por ano indepententemente do autor'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], default='A', max_length=1, verbose_name='Sequência de numeração de proposições'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='sequencia_numeracao_protocolo',
            field=models.CharField(choices=[('A', 'Sequencial por ano para cada autor'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], default='A', max_length=1, verbose_name='Sequência de numeração de protocolos'),
        ),
    ]
