# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20190417_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='sequencia_numeracao_proposicao',
            field=models.CharField(choices=[('A', 'Sequencial por ano para cada autor'), ('B', 'Sequencial por ano indepententemente do autor')], default='A', max_length=1, verbose_name='Sequência de numeração de proposições'),
        ),
    ]
