# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20190417_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='sequencia_numeracao_protocolo',
            field=models.CharField(choices=[('A', 'Sequencial por ano'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], default='A', max_length=1, verbose_name='Sequência de numeração de protocolos'),
        ),
    ]
