# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20190417_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='tramitacao_documento',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Tramitar documentos anexados junto com os documentos principais?'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tramitacao_materia',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Tramitar matérias anexadas junto com as matérias principais?'),
        ),
    ]
