# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20190527_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='cronometro_aparte',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='cronometro_consideracoes',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='cronometro_discurso',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='cronometro_ordem',
        ),
    ]
