# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-13 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migra_autores_usuarios(apps, schema_editor):
    Autor = apps.get_model('base', 'Autor')
    AutorUser = apps.get_model('base', 'AutorUser')

    for a in Autor.objects.filter(user__isnull=False):
        AutorUser.objects.create(autor=a, user=a.user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0038_auto_20190604_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Autor - Usuário',
                'verbose_name_plural': 'Autores - Usuários',
                'ordering': ('autor__nome',),
            },
        ),
        migrations.AlterField(
            model_name='autor',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='autoruser',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Autor', verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='autoruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuário'),
        ),
        migrations.RunPython(migra_autores_usuarios),
        migrations.RemoveField(
            model_name='autor',
            name='user',
        )
    ]
