# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-10 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0038_auto_20190604_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Autor', verbose_name='Autor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Autor - Usuário',
                'verbose_name_plural': 'Autores - Usuários',
                'ordering': ('autor__nome',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='autoruser',
            unique_together=set([('autor', 'user')]),
        ),
    ]
