# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-30 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auditlog'),
        ('base', '0039_auto_20190913_1228'),
    ]

    operations = [
    ]
