# Generated by Django 2.2 on 2020-05-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20191202_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='tipoautor',
            name='content_type',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Modelagem no SAPL'),
        ),
    ]
