# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20191202_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='registro_numeracao_materia',
            field=models.CharField(choices=[('N', 'Não registrar numeração'), ('A', 'Registrar numeração - sequencial por ano'), ('U', 'Registrar numeração - sequencial única')], default='N', max_length=1, verbose_name='Registro de numeração na criação de matérias'),
        ),
    ]
