# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20191202_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='inicio_numeracao_protocolo',
            field=models.PositiveIntegerField(default=1, verbose_name='Início da numeração de protocolo'),
        ),
    ]
