# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-10 14:13
from __future__ import unicode_literals

from django.db import migrations
from sapl.utils import get_settings_auth_user_model

def migra_autores_usuarios(apps, schema_editor):
    Autor = apps.get_model('base', 'Autor')
    AutorUser = apps.get_model('base', 'AutorUser')

    for a in Autor.objects.filter(user__isnull=False):
        AutorUser.objects.create(autor=a, user=a.user)
    

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20190910_1109'),
    ]

    operations = [
        migrations.RunPython(migra_autores_usuarios)
    ]
