# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20190910_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cargo'),
        ),
    ]
