# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_merge_20191030_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='assinatura_ata',
            field=models.CharField(choices=[('M', 'Mesa Diretora da Sessão'), ('P', 'Apenas o Presidente da Sessão'), ('T', 'Todos os Parlamentares Presentes na Sessão')], default='T', max_length=1, verbose_name='Quem deve assinar a ata'),
        ),
    ]
