# Generated by Django 2.2 on 2020-08-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_appconfig_inicio_numeracao_protocolo'),
        ('base', '0040_auto_20200521_1534'),
    ]

    operations = [
    ]
