# Generated by Django 2.2.13 on 2020-10-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_merge_20200818_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casalegislativa',
            options={'ordering': ('id',), 'verbose_name': 'Casa Legislativa', 'verbose_name_plural': 'Casa Legislativa'},
        ),
    ]
