# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20190911_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='user',
        ),
    ]
