# Generated by Django 2.2.13 on 2020-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_merge_20200818_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='registro_numeracao_materia',
            field=models.CharField(choices=[('N', 'Não registrar numeração'), ('A', 'Registrar numeração - sequencial por ano'), ('U', 'Registrar numeração - sequencial única')], default='N', max_length=1, verbose_name='Registro de numeração na criação de matérias'),
        ),
    ]
