# Generated by Django 2.2.13 on 2020-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_appconfig_registro_numeracao_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='registro_numeracao_materia',
            field=models.CharField(choices=[('N', 'Não registrar numeração de processo'), ('A', 'Registrar numeração de processo - sequencial por ano'), ('U', 'Registrar numeração de processo - sequencial única')], default='N', max_length=1, verbose_name='Registro de numeração de processo na criação de matérias'),
        ),
    ]
