# Generated by Django 2.2.13 on 2021-02-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20210203_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='sapl_as_sapn',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Utilizar SAPL com SAPN?'),
        ),
    ]
