# Generated by Django 2.2.13 on 2021-03-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_appconfig_sapl_as_sapn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='sapl_as_sapn',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Utilizar SAPL como SAPN?'),
        ),
    ]
