# Generated by Django 2.2.13 on 2021-03-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def adjust_user_oto_m2m(apps, schema_editor):
    Autor = apps.get_model('base', 'Autor')
    autores = Autor.objects.all()
    for a in autores:
        if a.user:
            a.operadores.add(a.user)


def adjust_remove_grupo_parlamentar(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Parlamentar').delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0045_auto_20210301_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorAutor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='operadorautor_set', to='base.Autor', verbose_name='Autor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='operadorautor_set', to=settings.AUTH_USER_MODEL, verbose_name='Operador do Autor')),
            ],
            options={
                'verbose_name': 'Operador do Autor',
                'verbose_name_plural': 'Operadores do Autor',
                'unique_together': {('user', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='operadores',
            field=models.ManyToManyField(
                related_name='autor_set', through='base.OperadorAutor', to=settings.AUTH_USER_MODEL),
        ),

        migrations.RunPython(adjust_user_oto_m2m),

        migrations.RunPython(adjust_remove_grupo_parlamentar),

        migrations.RemoveField(
            model_name='autor',
            name='user',
        ),

    ]
