# Generated by Django 2.2.13 on 2021-03-15 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20210314_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='operadores',
            field=models.ManyToManyField(related_name='autor_set', through='base.OperadorAutor', to=settings.AUTH_USER_MODEL, verbose_name='Operadores'),
        ),
    ]
