# Generated by Django 2.2.24 on 2021-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20210315_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='mostrar_campos_vazios_perfil_parlamentar',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Mostrar Campos sem Informação no Perfil do Parlamentar para Usuário não Logados?'),
        ),
    ]
