# Generated by Django 2.2.24 on 2021-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20210315_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='cronometro_personalizado',
            field=models.DurationField(blank=True, null=True, verbose_name='Cronômetro Personalizado'),
        ),
    ]
