# Generated by Django 2.2.28 on 2022-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20210315_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='tramitacao_origem_fixa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True,
                                      verbose_name='Fixar Origem das tramitações como sendo a tramitação de destino da última tramitação?'),
        ),
    ]
