# Generated by Django 2.2.28 on 2022-09-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20220814_2138'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS reversion_version"),
        migrations.RunSQL("DROP TABLE IF EXISTS reversion_revision"),
    ]
