# Generated by Django 2.2.28 on 2022-09-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20220919_1705'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS speedinfo_viewprofiler"),
    ]
