# Generated by Django 2.2.28 on 2022-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20220921_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='mostrar_voto',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Exibir voto do Parlamentar antes de encerrar a votação?'),
        ),
    ]
