# Generated by Django 2.2.28 on 2022-11-18 16:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_appconfig_mostrar_voto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-id', '-timestamp'), 'verbose_name': 'AuditLog', 'verbose_name_plural': 'AuditLogs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='data'),
        ),
    ]
