# Generated by Django 2.2.28 on 2023-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20221118_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='google_analytics_id_metrica',
            field=models.CharField(default='', max_length=256, verbose_name='ID da Métrica do Google Analytics'),
        ),
    ]
