# Generated by Django 2.2.28 on 2023-09-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_appconfig_google_analytics_id_metrica'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='ordenacao_pesquisa_materia',
            field=models.CharField(choices=[('S', 'Alfabética por Sigla'), ('R', 'Sequência Regimental')], default='S', max_length=1, verbose_name='Ordenação de Pesquisa da Matéria?'),
        ),
    ]
