# Generated by Django 2.2.28 on 2023-11-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_appconfig_ordenacao_pesquisa_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='sapl_as_sapn',
        ),
    ]
