# Generated by Django 2.2.28 on 2023-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20230829_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='ordem_sequencia_regimental',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, help_text='Ao utilizar a opção SIM, na tela de pesquisa da Matéria Legislativa, a ordem será da Sequencia Regimental, que foi, definido no cadastro de Tipo de Matéria Legislativa. Se informado NÃO, a ordem será Alfabética da Sigla.', verbose_name='Ordem da Matéria pela Sequência Regimental?'),
        ),
    ]
