# Generated by Django 2.2.28 on 2024-08-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_appconfig_sapl_as_sapn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='cep',
            field=models.CharField(blank=True, max_length=100, verbose_name='CEP'),
        ),
    ]
