# Generated by Django 2.2.28 on 2026-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20240812_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casalegislativa',
            name='informacao_geral',
            field=models.TextField(blank=True,
                                   verbose_name='Informação Geral'),
        ),
    ]
