# Generated by Django 2.2.28 on 2023-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20230829_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfig',
            name='ordem_sequencia_regimental',
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ordenacao_pesquisa_materia',
            field=models.CharField(choices=[('A', 'Alfabetica pela Sigla'), ('R', 'Sequencia Regimental')], default='A', max_length=1, verbose_name='Ordem de Pesquisa da Matéria?'),
        ),
    ]
