# Generated by Django 2.2.28 on 2026-04-18 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20240812_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('storage_name', models.CharField(max_length=512, verbose_name='Storage name')),
                ('original_filename', models.CharField(max_length=512, verbose_name='Original filename')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='File size (bytes)')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256 hash')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('backfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Backfilled at')),
            ],
            options={
                'verbose_name': 'File Metadata',
                'verbose_name_plural': 'File Metadata',
                'db_table': 'base_file_metadata',
            },
        ),
    ]
