# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0002_auto_20170330_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuntomateria',
            name='assunto',
            field=models.CharField(max_length=50, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='assuntomateria',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição do Dispositivo Legal'),
        ),
    ]
