# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0004_auto_20170504_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=sapl.materia.models.anexo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='texto_original',
            field=models.FileField(blank=True, null=True, upload_to=sapl.materia.models.materia_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='texto_original',
            field=models.FileField(blank=True, null=True, upload_to=sapl.materia.models.materia_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original'),
        ),
    ]
