# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-20 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproposicao',
            name='descricao',
            field=models.CharField(error_messages={'unique': 'Já existe um Tipo de Proposição com esta descrição.'}, max_length=50, unique=True, verbose_name='Descrição'),
        ),
    ]
