# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0007_auto_20170620_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
    ]
