# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0009_auto_20170712_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='arquivo',
            field=models.FileField(upload_to=sapl.materia.models.anexo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
        migrations.AlterField(
            model_name='documentoacessorio',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
