# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-08 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0010_auto_20170808_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoria',
            options={'ordering': ('-primeiro_autor', 'autor__nome'), 'verbose_name': 'Autoria', 'verbose_name_plural': 'Autorias'},
        ),
    ]
