# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-15 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0011_auto_20170808_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.TipoProposicao', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.StatusTramitacao', verbose_name='Status'),
        ),
    ]
