# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0012_auto_20170815_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_destino', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
        ),
    ]
