# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0013_adiciona_status_tramitacao'),
        ('materia', '0013_auto_20170905_0818'),
    ]

    operations = [
    ]
