# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0013_adiciona_status_tramitacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadetramitacao',
            options={'ordering': ['orgao', 'comissao', 'parlamentar'], 'verbose_name': 'Unidade de Tramitação', 'verbose_name_plural': 'Unidades de Tramitação'},
        ),
    ]
