# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0015_auto_20170908_1024'),
        ('materia', '0013_auto_20170816_1136'),
    ]

    operations = [
    ]
