# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0016_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='data_envio',
            field=models.DateTimeField(null=True, verbose_name='Data de Envio'),
        ),
    ]
