# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0017_acompanhamentomateria_confirmado'),
        ('materia', '0016_auto_20160225_0918'),
    ]

    operations = [
    ]
