# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0017_auto_20170918_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexada',
            name='materia_anexada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_anexada_set', to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='anexada',
            name='materia_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal_set', to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='autoria',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='autoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa', verbose_name='Matéria Legislativa'),
        ),
        migrations.AlterField(
            model_name='despachoinicial',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comissoes.Comissao'),
        ),
        migrations.AlterField(
            model_name='despachoinicial',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='documentoacessorio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='materiaassunto',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.AssuntoMateria', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='materiaassunto',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='numeracao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='relatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Relatoria'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='materia_de_vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposicao_set', to='materia.MateriaLegislativa', verbose_name='Matéria anexadora'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
    ]
