# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-27 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0018_auto_20171113_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexada',
            name='materia_anexada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_anexada_set', to='materia.MateriaLegislativa', verbose_name='Matéria Anexada'),
        ),
        migrations.AlterField(
            model_name='anexada',
            name='materia_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal_set', to='materia.MateriaLegislativa', verbose_name='Matéria Principal'),
        ),
    ]
