# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0019_auto_20171127_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='em_tramitacao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Em Tramitação?'),
        ),
    ]
