# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-06 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0021_auto_20180103_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='data',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data'),
        ),
    ]
