# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0023_auto_20160309_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeracao',
            name='data_materia',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
