# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0023_proposicao_hash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterialegislativa',
            name='sequencia_numeracao',
            field=models.CharField(blank=True, choices=[('A', 'Sequencial por ano'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], max_length=1, null=True, verbose_name='Sequência de numeração'),
        ),
    ]
