# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0024_tipomaterialegislativa_sequencia_numeracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterialegislativa',
            name='sequencia_numeracao',
            field=models.CharField(blank=True, choices=[('A', 'Sequencial por ano'), ('L', 'Sequencial por legislatura'), ('U', 'Sequencial único')], default='', max_length=1, verbose_name='Sequência de numeração'),
            preserve_default=False,
        ),
    ]
