# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0024_auto_20160311_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
    ]
