# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0025_auto_20180221_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeracao',
            name='data_materia',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
    ]
