# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0025_auto_20160311_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='data_tramitacao',
            field=models.DateField(verbose_name='Data Tramitação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.StatusTramitacao', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='texto',
            field=models.TextField(verbose_name='Texto da Ação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materia.UnidadeTramitacao', verbose_name='Unidade Local'),
        ),
    ]
