# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0026_auto_20160322_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='texto_original',
            field=models.FileField(blank=True, null=True, upload_to=sapl.materia.models.texto_upload_path, validators=[
                                   sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original (PDF)'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='texto_original',
            field=models.FileField(blank=True, null=True, upload_to=sapl.materia.models.texto_upload_path, validators=[
                                   sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original (PDF)'),
        ),
    ]
