# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0027_auto_20160404_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterialegislativa',
            name='num_automatica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipomaterialegislativa',
            name='quorum_minimo_votacao',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
