# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-01 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0028_auto_20180418_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regimetramitacao',
            options={'verbose_name': 'Regime de Tramitação', 'verbose_name_plural': 'Regimes de Tramitação'},
        ),
    ]
