# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0028_auto_20180418_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='data_tramitacao',
            field=models.DateTimeField(verbose_name='Data Tramitação'),
        ),
    ]
