# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0029_auto_20180901_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacao',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
