# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0029_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='tipo_origem_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_origem_externa_set', to='materia.TipoMateriaLegislativa', verbose_name='Tipo'),
        ),
    ]
