# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0030_tramitacao_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='unidade_deliberativa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Unidade Deliberativa'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='urgente',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Urgente ?'),
        ),
    ]
