# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0030_auto_20160429_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='urgente',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Urgente ?'),
        ),
    ]
