# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-22 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0031_auto_20180924_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoria',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Autor', verbose_name='Autor'),
        ),
    ]
