# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0031_auto_20180924_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
