# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0032_proposicao_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='cancelado',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Cancelada ?'),
        ),
    ]
