# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0033_documentoacessorio_texto_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoacessorio',
            old_name='texto_original',
            new_name='arquivo',
        ),
    ]
