# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-06 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0035_auto_20190104_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='data_apresentacao',
            field=models.DateField(verbose_name='Data de Apresentação'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='local_origem_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Origem', verbose_name='Local de Origem'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='numero_protocolo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número do Protocolo'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.TipoMateriaLegislativa', verbose_name='Tipo de Matéria Legislativa'),
        ),
    ]
