# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0036_auto_20190106_0330'),
        ('materia', '0034_auto_20190107_1402'),
    ]

    operations = [
    ]
