# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0036_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='texto_original',
            field=models.FileField(blank=True, null=True, upload_to=sapl.materia.models.texto_upload_path, validators=[
                                   sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original'),
        ),
    ]
