# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0034_auto_20190103_1446'),
        ('materia', '0036_auto_20190106_0330'),
    ]

    operations = [
    ]
