# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0037_auto_20160520_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustramitacao',
            name='indicador',
            field=models.CharField(blank=True, choices=[('F', 'Fim'), ('R', 'Retorno')], max_length=1, verbose_name='Indicador da Tramitação'),
        ),
    ]
