# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0038_auto_20190108_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproposicao',
            name='content_type',
            field=models.ForeignKey(default=None, help_text='\n        Quando uma proposição é incorporada, ela é convertida de proposição\n        para outro elemento dentro do Sapl. Existem alguns elementos que\n        uma proposição pode se tornar. Defina este meta-tipo e em seguida\n        escolha um Tipo Correspondente!\n        ', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Conversão de Meta-Tipos'),
        ),
    ]
