# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0039_auto_20190209_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='turno',
            field=models.CharField(blank=True, choices=[('P', 'Primeiro'), ('S', 'Segundo'), ('U', 'Único'), ('L', 'Suplementar'), ('F', 'Final'), ('A', 'Votação única em Regime de Urgência'), ('B', '1ª Votação'), ('C', '2ª e 3ª Votação'), ('D', 'Deliberação'), ('E', '1ª e 2ª votações em regime de urgência')], max_length=1, verbose_name='Turno'),
        ),
    ]
