# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0040_auto_20190211_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='numero_materia_futuro',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número Matéria'),
        ),
    ]
