# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0041_remove_proposicao_data_incorporação'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='data_devolução',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução'),
        ),
    ]
