# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0042_proposicao_data_devolução'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposicao',
            old_name='data_devolução',
            new_name='data_devolucao',
        ),
    ]
