# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0042_tipomaterialegislativa_sequencia_regimental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipomaterialegislativa',
            options={'ordering': ['sequencia_regimental', 'descricao'], 'verbose_name': 'Tipo de Matéria Legislativa', 'verbose_name_plural': 'Tipos de Matérias Legislativas'},
        ),
    ]
