# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0039_auto_20160628_1251'),
        ('materia', '0043_auto_20160810_1738'),
    ]

    operations = [
    ]
