# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0046_auto_20160825_1833'),
        ('materia', '0046_auto_20160825_1504'),
    ]

    operations = [
    ]
