# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0046_auto_20190417_1212'),
        ('materia', '0047_auto_20190417_1432'),
    ]

    operations = [
    ]
