# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0048_auto_20160927_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoria',
            name='partido',
        ),
    ]
