# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0019_auto_20181214_1023'),
        ('materia', '0048_merge_20190426_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PautaReuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_set', to='materia.MateriaLegislativa', verbose_name='Matéria')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniao_set', to='comissoes.Reuniao', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Matéria da Pauta',
                'verbose_name_plural': 'Matérias da Pauta',
            },
        ),
    ]
