# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0050_auto_20190521_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachoinicial',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
    ]
