# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0050_auto_20161003_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'ordering': ('-data_tramitacao',), 'verbose_name': 'Tramitação', 'verbose_name_plural': 'Tramitações'},
        ),
    ]
