# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0051_auto_20161004_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regimetramitacao',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
