# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-31 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0052_auto_20190731_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='ultima_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
    ]
