# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0052_tramitacao_ultima_edicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialegislativa',
            name='ultima_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
    ]
