# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0052_auto_20161004_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'verbose_name': 'Tramitação', 'verbose_name_plural': 'Tramitações'},
        ),
    ]
