# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0052_auto_20190712_1053'),
        ('materia', '0053_proposicao_ultima_edicao'),
    ]

    operations = [
    ]
