# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0053_auto_20161004_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='em_tramitacao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Em Tramitação?'),
        ),
    ]
