# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-16 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0054_merge_20190802_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialegislativa',
            options={'ordering': ['-id'], 'permissions': (('can_access_impressos', 'Can access impressos'),), 'verbose_name': 'Matéria Legislativa', 'verbose_name_plural': 'Matérias Legislativas'},
        ),
    ]
