# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0053_materialegislativa_ultima_edicao'),
        ('materia', '0054_merge_20190802_1112'),
    ]

    operations = [
    ]
