# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0055_auto_20190816_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTurnoTramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Turno')),
            ],
            options={
                'verbose_name': 'Tipo de Turno de Tramitação',
                'verbose_name_plural': 'Tipos de Turno de Tramitação',
            },
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.TipoTurnoTramitacao', verbose_name='Turno'),
        ),
    ]
