# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 19:45
from __future__ import unicode_literals

from django.db import migrations


def clear_model_tipo_proposicao(apps, schema_editor):
    TipoProposicao = apps.get_model("materia", "TipoProposicao")
    TipoProposicao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0056_merge'),
    ]

    operations = [
        migrations.RunPython(clear_model_tipo_proposicao), ]
