# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0055_auto_20161009_1418'),
        ('materia', '0054_auto_20161011_0904'),
    ]

    operations = [
    ]
