# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0055_auto_20190816_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialegislativa',
            name='ultima_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='ultima_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
    ]
