# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def clear_model_tipo_proposicao(apps, schema_editor):
    TipoProposicao = apps.get_model("materia", "TipoProposicao")
    TipoProposicao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('materia', '0056_remove_tipo_proposicao'),
    ]

    operations = [
        migrations.RunPython(clear_model_tipo_proposicao),
        migrations.RemoveField(
            model_name='tipoproposicao',
            name='materia_ou_documento',
        ),
        migrations.RemoveField(
            model_name='tipoproposicao',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='tipoproposicao',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='tipoproposicao',
            name='tipo_materia',
        ),
        migrations.AddField(
            model_name='tipoproposicao',
            name='conteudo',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Conteúdo'),
        ),
    ]
