# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0057_materiaemtramitacao'),
        ('materia', '0056_auto_20190829_1206'),
    ]

    operations = [
    ]
