# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0057_auto_20161016_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproposicao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproposicao',
            name='conteudo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Definição de Tipo'),
        ),
    ]
