# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0057_materiaemtramitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='turno',
            field=models.CharField(blank=True, choices=[('P', 'Primeiro'), ('S', 'Segundo'), ('U', 'Único'), ('L', 'Suplementar'), ('F', 'Final'), ('A', 'Votação Única em Regime de Urgência'), ('B', '1ª Votação'), ('C', '2ª e 3ª Votações'), ('D', 'Deliberação'), ('G', '1ª e 2ª Votações'), ('E', '1ª e 2ª Votações em Regime de Urgência')], max_length=1, verbose_name='Turno'),
        ),
    ]
