# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0058_auto_20191001_1450'),
        ('materia', '0058_auto_20191001_1115'),
    ]

    operations = [
    ]