# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0058_auto_20191001_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='texto_original',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.materia.models.materia_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='texto_original',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.materia.models.materia_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Original'),
        ),
    ]
