# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0058_auto_20161016_0329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipoproposicao',
            unique_together=set([('conteudo', 'object_id')]),
        ),
    ]
