# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-30 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0059_merge_20191003_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto da Ação'),
        ),
    ]