# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0060_auto_20161017_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
