# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0060_auto_20190930_1136'),
        ('materia', '0058_merge_20190926_1250'),
    ]

    operations = [
    ]
