# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.materia.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0061_auto_20191023_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='arquivo',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.materia.models.anexo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
    ]
