# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-06 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0061_auto_20190905_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacao',
            name='turno',
        ),
    ]
