# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-09 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0061_auto_20191120_1440'),
        ('materia', '0061_merge_20191009_1814'),
    ]

    operations = [
    ]
