# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0062_auto_20161021_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposicao',
            name='materia',
        ),
        migrations.AddField(
            model_name='proposicao',
            name='materia_vinculada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposicao_set', to='materia.MateriaLegislativa', verbose_name='Matéria Vinculada'),
        ),
    ]
