# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0062_merge_20191209_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pautareuniao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_set', to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
    ]
