# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0062_remove_tramitacao_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto da Ação'),
        ),
    ]
