# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('materia', '0063_auto_20161021_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='materia_de_vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposicao_set', to='materia.MateriaLegislativa', verbose_name='Matéria anexadora'),
        ),
        migrations.AddField(
            model_name='proposicao',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='documento_gerado',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='materia_gerada',
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='materia_vinculada',
        ),
        migrations.AlterUniqueTogether(
            name='proposicao',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
