# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-21 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0063_auto_20191010_1228'),
        ('materia', '0061_auto_20191118_2036'),
    ]

    operations = [
    ]
