# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-17 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0064_remove_tramitacao_turno'),
        ('materia', '0061_merge_20191009_1814'),
    ]

    operations = [
    ]
