# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0061_auto_20191120_1440'),
        ('materia', '0064_merge_20191121_1346'),
    ]

    operations = [
    ]
