# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-13 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0064_merge_20200114_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assuntomateria',
            options={'ordering': ('assunto', 'dispositivo'), 'verbose_name': 'Assunto de Matéria', 'verbose_name_plural': 'Assuntos de Matéria'},
        ),
        migrations.AlterModelOptions(
            name='materiaassunto',
            options={'ordering': ('assunto__assunto', '-materia'), 'verbose_name': 'Relação Matéria - Assunto', 'verbose_name_plural': 'Relações Matéria - Assunto'},
        ),
    ]
