# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-13 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0065_auto_20200313_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='descricao',
            field=models.TextField(verbose_name='Ementa'),
        ),
    ]
