# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0066_auto_20200313_1441'),
        ('materia', '0065_auto_20200114_1125'),
    ]

    operations = [
    ]
