# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0066_auto_20200313_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
    ]
