# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0066_proposicao_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproposicao',
            old_name='conteudo',
            new_name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='tipoproposicao',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
