# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _
import django.db.models.deletion


def migra_tipos_turnos_tramitacao(apps, schema_editor):
    TipoTurnoTramitacao = apps.get_model('materia', 'TipoTurnoTramitacao')
    Tramitacao = apps.get_model('materia', 'Tramitacao')

    TURNO_CHOICES = {
        'P': _('Primeiro'),
        'S': _('Segundo'),
        'U': _('Único'),
        'L': _('Suplementar'),
        'F': _('Final'),
        'A': _('Votação Única em Regime de Urgência'),
        'B': _('1ª Votação'),
        'C': _('2ª e 3ª Votações'),
        'D': _('Deliberação'),
        'G': _('1ª e 2ª Votações'),
        'E': _('1ª e 2ª Votações em Regime de Urgência'),
    }
    
    for value in TURNO_CHOICES.values():
        TipoTurnoTramitacao.objects.create(nome=value)

    for t in Tramitacao.objects.all():
        turno_antigo = t.turno
        if turno_antigo:
            try:
                t.tipo_turno = TipoTurnoTramitacao.objects.get(nome=TURNO_CHOICES[turno_antigo])
            except Exception:
                continue
            else:
                t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0067_auto_20200416_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTurnoTramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Turno')),
            ],
            options={
                'verbose_name': 'Tipo de Turno de Tramitação',
                'verbose_name_plural': 'Tipos de Turno de Tramitação',
            },
        ),
        migrations.AddField(
            model_name='tramitacao',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.TipoTurnoTramitacao', verbose_name='Turno'),
        ),
        migrations.RunPython(migra_tipos_turnos_tramitacao),
        migrations.RemoveField(
            model_name='tramitacao',
            name='turno',
        ),
    ]
