# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0067_auto_20200416_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEtiquetaMateriaLegislativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.FloatField(default=5)),
                ('altura', models.FloatField(default=3)),
            ],
        ),
    ]
