# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0067_auto_20200416_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEtiquetaMateriaLegislativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.FloatField()),
                ('altura', models.FloatField()),
                ('mostrar_em_arquivo', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Mostrar em arquivo ?')),
            ],
        ),
    ]
