# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 15:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0067_auto_20200401_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaProtocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_materia', models.PositiveIntegerField()),
                ('ano_materia', models.PositiveIntegerField()),
                ('numero_protocolo', models.PositiveIntegerField()),
                ('ano_protocolo', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'materia_materiaprotocolo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtocoloMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.PositiveIntegerField()),
                ('ano_protocolo', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('materias', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), size=None)),
            ],
            options={
                'db_table': 'materia_protocolomateria',
                'managed': False,
            },
        ),
    ]
