# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 18:19
from __future__ import unicode_literals

from django.db import migrations


def create_first(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Type = apps.get_model("materia", "ConfigEtiquetaMateriaLegislativa")
    Type.objects.using(db_alias).create()

class Migration(migrations.Migration):
    dependencies = [
        ('materia', '0068_configetiquetamaterialegislativa'),
    ]

    operations = [
        migrations.RunPython(create_first),
    ]