# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0069_tipoproposicao_perfis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproposicao',
            name='perfis',
            field=models.ManyToManyField(blank=True, help_text='\n                    Mesmo que em Configurações da Aplicação nas\n                    Tabelas Auxiliares esteja definido que Proposições possam\n                    utilizar Textos Articulados, ao gerar uma proposição,\n                    a solução de Textos Articulados será disponibilizada se\n                    o Tipo escolhido para a Proposição estiver associado a ao\n                    menos um Perfil Estrutural de Texto Articulado.\n                    ',
                                         to='compilacao.PerfilEstruturalTextoArticulado', verbose_name='Perfis Estruturais de Textos Articulados'),
        ),
    ]
