# Generated by Django 2.2 on 2020-05-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0069_auto_20200518_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Tipo de Material Gerado'),
        ),
    ]
