# Generated by Django 2.2 on 2020-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0070_auto_20200521_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialegislativa',
            name='complementar',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É Complementar?'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='polemica',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Matéria Polêmica?'),
        ),
    ]
