# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0071_auto_20161130_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposicao',
            options={'permissions': (('detail_proposicao_enviada', 'Pode acessar detalhes de uma proposição enviada.'), ('detail_proposicao_devolvida', 'Pode acessar detalhes de uma proposição devolvida.'), ('detail_proposicao_incorporada', 'Pode acessar detalhes de uma proposição incorporada.')), 'verbose_name': 'Proposição', 'verbose_name_plural': 'Proposições'},
        ),
    ]
