# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0072_auto_20161130_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustramitacao',
            options={'ordering': ['descricao'], 'verbose_name': 'Status de Tramitação', 'verbose_name_plural': 'Status de Tramitação'},
        ),
        migrations.AlterModelOptions(
            name='tipomaterialegislativa',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Matéria Legislativa', 'verbose_name_plural': 'Tipos de Matérias Legislativas'},
        ),
    ]
