# Generated by Django 2.2.13 on 2020-09-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0072_auto_20200902_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tramitacao',
            options={'ordering': ('-data_tramitacao', '-id'), 'verbose_name': 'Tramitação', 'verbose_name_plural': 'Tramitações'},
        ),
    ]
