# Generated by Django 2.2.13 on 2020-10-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0073_auto_20200910_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoacessorio',
            options={'ordering': ('data', '-data_ultima_atualizacao'), 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
    ]
