# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0075_auto_20170203_1019'),
        ('materia', '0075_auto_20170123_1548'),
    ]

    operations = [
    ]
