# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0076_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoria',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
    ]
