# Generated by Django 2.2.13 on 2021-03-02 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materia', '0077_auto_20210209_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoProposicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Enviada'), ('R', 'Recebida'), ('T', 'Retornada'), ('D', 'Devolvida')], db_index=True, max_length=1, verbose_name='Status de Proposição')),
                ('data_hora', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Data/Hora')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('ip', models.CharField(blank=True, default='', max_length=60, verbose_name='IP')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.Proposicao', verbose_name='Proposição')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Proposição',
                'verbose_name_plural': 'Histórico de Proposições',
                'ordering': ('-data_hora', '-proposicao'),
            },
        ),
    ]
