# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0077_auto_20170321_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamentomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='anexada',
            name='materia_anexada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_anexada_set', to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='anexada',
            name='materia_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materia_principal_set', to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='autoria',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='autoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa', verbose_name='Matéria Legislativa'),
        ),
        migrations.AlterField(
            model_name='despachoinicial',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.Comissao'),
        ),
        migrations.AlterField(
            model_name='despachoinicial',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='documentoacessorio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='documentoacessorio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.TipoDocumento', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='materiaassunto',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.AssuntoMateria'),
        ),
        migrations.AlterField(
            model_name='materiaassunto',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='local_origem_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Origem', verbose_name='Local Origem'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='regime_tramitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.RegimeTramitacao', verbose_name='Regime Tramitação'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.TipoMateriaLegislativa', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='materialegislativa',
            name='tipo_origem_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipo_origem_externa_set', to='materia.TipoMateriaLegislativa', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='numeracao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='numeracao',
            name='tipo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.TipoMateriaLegislativa', verbose_name='Tipo de Matéria'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='parecer',
            name='relatoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.Relatoria'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='materia_de_vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposicao_set', to='materia.MateriaLegislativa', verbose_name='Matéria anexadora'),
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.TipoProposicao', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='relatoria',
            name='tipo_fim_relatoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.TipoFimRelatoria', verbose_name='Motivo Fim Relatoria'),
        ),
        migrations.AlterField(
            model_name='tipoproposicao',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='Definição de Tipo'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.StatusTramitacao', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_destino', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_origem', to='materia.UnidadeTramitacao', verbose_name='Unidade Local'),
        ),
        migrations.AlterField(
            model_name='unidadetramitacao',
            name='comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='unidadetramitacao',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Orgao', verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='unidadetramitacao',
            name='parlamentar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
