# Generated by Django 2.2.13 on 2021-03-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0078_historicoproposicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=256, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='sigla',
            field=models.CharField(max_length=15, verbose_name='Sigla'),
        ),
    ]
