# Generated by Django 2.2.24 on 2021-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0079_auto_20210311_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='indexacao',
            field=models.TextField(blank=True, verbose_name='Indexação'),
        ),
    ]
