# Generated by Django 2.2.20 on 2021-08-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0039_documentoacessorio_reuniao'),
        ('materia', '0079_auto_20210311_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='PautaReuniaoFrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa', verbose_name='Matéria')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Reuniao', verbose_name='Reunião')),
            ],
            options={
                'verbose_name': 'Matéria da Pauta',
                'verbose_name_plural': 'Matérias da Pauta',
                'ordering': ('id',),
            },
        ),
    ]
