# Generated by Django 2.2.28 on 2022-09-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0081_auto_20220321_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='justificativa_restricao',
            field=models.TextField(blank=True, verbose_name='Justificativa de Restrição'),
        ),
        migrations.AddField(
            model_name='documentoacessorio',
            name='restrito',
            field=models.BooleanField(blank=True, default=False, verbose_name='Restrito'),
        ),
    ]
