# Generated by Django 2.2.28 on 2023-10-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0083_auto_20230731_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
    ]
