# Generated by Django 2.2.28 on 2023-10-28 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0084_auto_20231007_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeracao',
            name='tipo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.TipoMateriaLegislativa', verbose_name='Tipo de Matéria'),
        ),
    ]
