# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-27 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0086_auto_20240711_1400'),
    ]

    operations = [
        migrations.RunSQL("""
            create or replace view materia_materiaemtramitacao as
            select m.id as id,
                   m.id as materia_id,
                   t.id as tramitacao_id,
                   t.unidade_tramitacao_destino_id as unidade_tramitacao_atual_id
            from materia_materialegislativa m
            inner join materia_tramitacao t on (m.id = t.materia_id)
            where t.id = (select max(id) from materia_tramitacao where materia_id = m.id)
            order by m.id DESC
        """),
    ]