# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0050_auto_20191029_1441'),
        ('sdr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconferencia',
            name='sessao_plenaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria', verbose_name='Sessão Plenária'),
        ),
    ]
