# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdr', '0003_auto_20200331_1926'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SistemaDeliberacaoRemota',
            new_name='DeliberacaoRemota',
        ),
        migrations.AlterModelOptions(
            name='deliberacaoremota',
            options={'ordering': ['chat_id', 'descricao'], 'verbose_name': 'Deliberação Remota', 'verbose_name_plural': 'Deliberações Remotas'},
        ),
    ]
