# Generated by Django 2.2.13 on 2020-10-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20180523_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronometro',
            options={'ordering': ('-data_cronometro',)},
        ),
        migrations.AlterModelOptions(
            name='painel',
            options={'ordering': ('-data_painel',)},
        ),
    ]
