# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_auto_20180523_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronometro',
            options={'ordering': ['ordenacao'], 'verbose_name': 'Cronômetro', 'verbose_name_plural': 'Cronômetros'},
        ),
        migrations.RemoveField(
            model_name='cronometro',
            name='data_cronometro',
        ),
        migrations.AddField(
            model_name='cronometro',
            name='ativo',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='cronometro',
            name='duracao_cronometro',
            field=models.DurationField(verbose_name='Duração do cronômetro'),
        ),
        migrations.AddField(
            model_name='cronometro',
            name='ordenacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordenação'),
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='status',
            field=models.CharField(choices=[('I', 'Start'), ('R', 'Reset'), ('S', 'Stop'), ('C', 'Increment')], default='S', max_length=1, verbose_name='Status do cronômetro'),
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='tipo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo Cronômetro'),
        ),
    ]
