# Generated by Django 2.2.24 on 2021-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_auto_20201013_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronometro',
            name='tempo_restante',
            field=models.DurationField(blank=True, null=True, verbose_name='Tempo restante no cronômetro'),
        ),
    ]
