# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 13:33
from __future__ import unicode_literals

from django.db import migrations


def create_default_cronometros(apps, schema_editor):
    tipos_default = ['Cronômetro do Discurso', 'Cronômetro do Aparte', 
                     'Cronômetro da Questão de Ordem', 'Cronômetro de Considerações Finais']
    Cronometro = apps.get_model('painel', 'Cronometro')
    
    for i,tipo in enumerate(tipos_default):
        Cronometro.objects.get_or_create(tipo=tipo, duracao_cronometro='00:05:00', status='S', ativo=True, ordenacao=i+1)


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_auto_20190603_1033'),
    ]

    operations = [
        migrations.RunPython(create_default_cronometros)
    ]
