# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_auto_20190603_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCronometro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo Cronômetro')),
            ],
            options={
                'verbose_name': 'Tipo de Cronômetro',
                'verbose_name_plural': 'Tipos de Cronômetro',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='painel.TipoCronometro', verbose_name='Tipo Cronômetro'),
        ),
    ]
