# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 11:42
from __future__ import unicode_literals

from django.db import migrations


def create_default_tipos_cronometro(apps, schema_editor):
    TipoCronometro = apps.get_model('painel', 'TipoCronometro')
    tipos_default = ['Cronômetro do Discurso', 'Cronômetro do Aparte', 
                     'Cronômetro da Ordem', 'Cronômetro de Considerações Finais']
    for tipo in tipos_default:
        TipoCronometro.objects.get_or_create(nome=tipo)


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_auto_20190603_0826'),
    ]

    operations = [
         migrations.RunPython(create_default_tipos_cronometro)
    ]
