# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_auto_20190612_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelconfig',
            name='tempo_disparo_termino',
            field=models.DurationField(blank=True, default='00:00:05', null=True, verbose_name='Cronômetros devem permanecer tocando por quanto tempo ao término?'),
        ),
    ]
