# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_painelconfig_tempo_disparo_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelconfig',
            name='exibir_nome_casa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Exibir nome da Casa Legislativa no painel?'),
        ),
    ]
