# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_painelconfig_exibir_nome_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelconfig',
            name='mostrar_votos_antecedencia',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Mostrar votos informados antes do fim da votação?'),
        ),
    ]
