# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_painelconfig_mostrar_votos_antecedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronometro',
            name='ultima_alteracao_status',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='status',
            field=models.CharField(choices=[('I', 'Start'), ('R', 'Reset'), ('S', 'Stop'), ('C', 'Increment')], default='R', max_length=1, verbose_name='Status do cronômetro'),
        ),
    ]
