# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_auto_20190711_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronometro',
            name='last_stop_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Última duração salva em stop'),
        ),
    ]
