# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_cronometro_last_stop_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='painelconfig',
            name='mostrar_ementa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Mostrar ementa da matéria?'),
        ),
    ]
