# Generated by Django 2.2.28 on 2023-07-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('publico', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], db_index=True, default=True, verbose_name='Público')),
                ('privado', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], db_index=True, default=True, verbose_name='Público')),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatórios',
                'ordering': ['nome'],
            },
        ),
    ]
