# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0007_auto_20160218_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='ano',
            field=models.PositiveSmallIntegerField(verbose_name='Ano do Protocolo'),
        ),
    ]
