# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0012_auto_20160503_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitacaoadministrativo',
            name='ultima',
        ),
    ]
