# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0013_remove_tramitacaoadministrativo_ultima'),
        ('protocoloadm', '0013_merge'),
    ]

    operations = [
    ]
