# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0044_auto_20160307_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoarticulado',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
