# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0044_auto_20160307_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='dispositivo_subsequente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compilacao.Dispositivo', verbose_name='Dispositivo Subsequente'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='dispositivo_substituido',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compilacao.Dispositivo', verbose_name='Dispositivo Substituido'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='inconstitucionalidade',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Declaração de Inconstitucionalidade'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='texto',
            field=models.TextField(blank=True, default='', verbose_name='Texto na Norma Original'),
        ),
    ]
