# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='texto_integral',
            field=models.FileField(blank=True, null=True, upload_to=sapl.utils.texto_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
    ]
