# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-22 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.norma.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0003_auto_20170510_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='texto_integral',
            field=models.FileField(blank=True, null=True, upload_to=sapl.norma.models.norma_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
