# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-23 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0004_auto_20170522_1115'),
        ('norma', '0004_auto_20170522_1051'),
    ]

    operations = [
    ]
