# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data'),
        ),
    ]
