# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0006_normajuridica_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assuntonorma',
            options={'ordering': ['assunto'], 'verbose_name': 'Assunto de Norma Jurídica', 'verbose_name_plural': 'Assuntos de Normas Jurídicas'},
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='esfera_federacao',
            field=models.CharField(choices=[('M', 'Municipal'), ('E', 'Estadual'), ('F', 'Federal')], max_length=1, verbose_name='Esfera Federação'),
        ),
    ]
