# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0008_normajuridica_popula_tipo_vinculo_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislacaocitada',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='legislacaocitada',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.NormaJuridica'),
        ),
    ]
