# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0010_auto_20160216_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 3, 7, 14, 53, 52, 206255, tzinfo=utc), verbose_name='Data'),
            preserve_default=False,
        ),
    ]
