# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-20 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0010_auto_20180103_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='data',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
    ]
