# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0012_anexonormajuridica'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexonormajuridica',
            name='assunto_anexo',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Assunto do Anexo'),
        ),
    ]
