# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0012_anexonormajuridica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexonormajuridica',
            options={'verbose_name': 'Anexo da Norma Jurídica', 'verbose_name_plural': 'Anexos da Norma Jurídica'},
        ),
        migrations.AlterField(
            model_name='anexonormajuridica',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norma', to='norma.NormaJuridica', verbose_name='Norma Jurídica'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='norma.TipoNormaJuridica', verbose_name='Tipo da Norma Jurídica'),
        ),
    ]
