# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_appconfig_esfera_federacao'),
        ('norma', '0013_anexonormajuridica_assunto_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoriaNorma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_autor', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Primeiro Autor')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Autor', verbose_name='Autor')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.NormaJuridica', verbose_name='Matéria Legislativa')),
            ],
            options={
                'ordering': ('-primeiro_autor', 'autor__nome'),
                'verbose_name': 'Autoria',
                'verbose_name_plural': 'Autorias',
            },
        ),
        migrations.AddField(
            model_name='normajuridica',
            name='autores',
            field=models.ManyToManyField(through='norma.AutoriaNorma', to='base.Autor'),
        ),
        migrations.AlterUniqueTogether(
            name='autorianorma',
            unique_together=set([('autor', 'norma')]),
        ),
    ]
