# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0014_auto_20181008_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='data_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data Fim Vigência'),
        ),
    ]
