# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-23 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0015_auto_20181109_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovinculonormajuridica',
            name='revoga_integramente',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Revoga Integralmente?'),
        ),
    ]
