# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0015_auto_20160929_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assuntonormarelationship',
            options={'verbose_name': 'Assunto', 'verbose_name_plural': 'Assuntos'},
        ),
        migrations.AlterUniqueTogether(
            name='assuntonormarelationship',
            unique_together=set([]),
        ),
    ]
