# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-27 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0016_tipovinculonormajuridica_revoga_integramente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovinculonormajuridica',
            old_name='revoga_integramente',
            new_name='revoga_integralmente',
        ),
    ]
