# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0016_auto_20161027_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='assuntos',
            field=models.ManyToManyField(through='norma.AssuntoNormaRelationship', to='norma.AssuntoNorma', verbose_name='Assuntos'),
        ),
    ]
