# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0017_auto_20161027_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assuntonormarelationship',
            name='assunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.AssuntoNorma', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='assuntonormarelationship',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.NormaJuridica', verbose_name='Norma'),
        ),
    ]
