# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0018_normaestatisticas_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaestatisticas',
            name='horario_acesso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
