# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0019_auto_20161028_0232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assuntonormarelationship',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='assuntonormarelationship',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='assuntonormarelationship',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='normajuridica',
            name='assuntos',
        ),
        migrations.AddField(
            model_name='normajuridica',
            name='assuntos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AssuntoNormaRelationship',
        ),
    ]
