# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0018_auto_20190103_1446'),
        ('norma', '0020_auto_20190106_0454'),
    ]

    operations = [
    ]
