# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0022_auto_20161110_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculonormajuridica',
            options={'verbose_name': 'Tipo de Vínculo entre Normas Jurídicas', 'verbose_name_plural': 'Tipos de Vínculos entre Normas Jurídicas'},
        ),
        migrations.RemoveField(
            model_name='vinculonormajuridica',
            name='norma_referente',
        ),
        migrations.RemoveField(
            model_name='vinculonormajuridica',
            name='norma_referida',
        ),
        migrations.RemoveField(
            model_name='vinculonormajuridica',
            name='tipo_vinculo',
        ),
        migrations.AddField(
            model_name='vinculonormajuridica',
            name='descricao',
            field=models.CharField(blank=True, max_length=20, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='vinculonormajuridica',
            name='sigla',
            field=models.CharField(blank=True, max_length=1, verbose_name='Nome'),
        ),
    ]
