# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0022_auto_20190108_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normarelacionada',
            options={'ordering': ('norma_principal__ano', 'norma_relacionada__ano'), 'verbose_name': 'Norma Relacionada', 'verbose_name_plural': 'Normas Relacionadas'},
        ),
    ]
