# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0023_auto_20161123_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculonormajuridica',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='vinculonormajuridica',
            name='sigla',
            field=models.CharField(blank=True, max_length=1, verbose_name='Sigla'),
        ),
    ]
