# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('norma', '0024_auto_20190425_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='normajuridica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
