# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0024_auto_20161123_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaRelacionada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norma_principal', to='norma.NormaJuridica')),
                ('norma_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norma_relacionada', to='norma.NormaJuridica')),
                ('tipo_vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.VinculoNormaJuridica')),
            ],
            options={
                'verbose_name': 'Norma Relacionada',
                'verbose_name_plural': 'Normas Relacionadas',
            },
        ),
    ]
