# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0025_normajuridica_norma_de_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='apelido',
            field=models.TextField(blank=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='norma_de_destaque',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Norma de Destaque ?'),
        ),
    ]
