# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0025_auto_20190704_0816'),
        ('norma', '0025_auto_20190704_1403'),
    ]

    operations = [
    ]
