# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0025_normarelacionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normarelacionada',
            name='tipo_vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norma.VinculoNormaJuridica', verbose_name='Tipo de Vínculo'),
        ),
    ]
