# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0026_auto_20190712_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='anulada',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Anulada ?'),
        ),
    ]
