# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0026_auto_20161123_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normarelacionada',
            name='norma_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norma_principal', to='norma.NormaJuridica', verbose_name='Norma Principal'),
        ),
        migrations.AlterField(
            model_name='normarelacionada',
            name='norma_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norma_relacionada', to='norma.NormaJuridica', verbose_name='Norma Relacionada'),
        ),
    ]
