# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0026_auto_20190712_1053'),
        ('norma', '0026_merge_20190708_1120'),
    ]

    operations = [
    ]
