# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0027_merge_20190802_1117'),
        ('norma', '0027_auto_20191001_1115'),
    ]

    operations = [
    ]
