# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0027_auto_20161123_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
    ]
