# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0027_normajuridica_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='anulada',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Anulada'),
        ),
    ]
