# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0027_normajuridica_ultima_edicao'),
        ('norma', '0027_auto_20191001_1115'),
    ]

    operations = [
    ]
