# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0028_auto_20161202_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiponormajuridica',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Norma Jurídica', 'verbose_name_plural': 'Tipos de Norma Jurídica'},
        ),
    ]
