# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0029_auto_20191024_1344'),
        ('norma', '0028_merge_20191003_0909'),
    ]

    operations = [
    ]
