# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0030_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='numero',
            field=models.CharField(max_length=8, verbose_name='Número'),
        ),
    ]
