# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-10 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0031_auto_20161219_1324'),
        ('norma', '0030_auto_20170102_0951'),
    ]

    operations = [
    ]
