# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0031_auto_20200114_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='veiculo_publicacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Veículo de Publicação'),
        ),
    ]
