# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0032_auto_20200114_1125'),
        ('norma', '0032_auto_20200221_1533'),
    ]

    operations = [
    ]
