# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0032_auto_20200221_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
    ]
