# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0033_auto_20200416_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='apelido',
            field=models.TextField(blank=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='normajuridica',
            name='norma_de_destaque',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Norma de Destaque ?'),
        ),
    ]
