# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0033_auto_20170203_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculonormajuridica',
            name='descricao',
        ),
        migrations.AddField(
            model_name='vinculonormajuridica',
            name='descricao_ativa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descrição Ativa'),
        ),
        migrations.AddField(
            model_name='vinculonormajuridica',
            name='descricao_passiva',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descrição Passiva'),
        ),
    ]
