# Generated by Django 2.2 on 2020-06-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0033_auto_20200416_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='complemento',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=None, null=True, verbose_name='Complementar ?'),
        ),
    ]
