# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0034_auto_20170222_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VinculoNormaJuridica',
            new_name='TipoVinculoNormaJuridica',
        ),
    ]
