# Generated by Django 2.2 on 2020-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0034_auto_20200609_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='complemento',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Complementar ?'),
        ),
    ]
