# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0036_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislacaocitada',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='legislacaocitada',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='norma.NormaJuridica'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='normajuridica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='norma.TipoNormaJuridica', verbose_name='Tipo da Norma Juridica'),
        ),
        migrations.AlterField(
            model_name='normarelacionada',
            name='norma_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norma_principal', to='norma.NormaJuridica', verbose_name='Norma Principal'),
        ),
        migrations.AlterField(
            model_name='normarelacionada',
            name='norma_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norma_relacionada', to='norma.NormaJuridica', verbose_name='Norma Relacionada'),
        ),
        migrations.AlterField(
            model_name='normarelacionada',
            name='tipo_vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='norma.TipoVinculoNormaJuridica', verbose_name='Tipo de Vínculo'),
        ),
    ]
