# Generated by Django 2.2.13 on 2021-03-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0077_auto_20210209_1047'),
        ('norma', '0037_auto_20210107_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='normajuridica',
            name='orgao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Orgao', verbose_name='Órgão'),
        ),
    ]
