# Generated by Django 2.2.28 on 2022-07-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0039_auto_20220321_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='normarelacionada',
            name='resumo',
            field=models.TextField(blank=True, default='', verbose_name='Resumo'),
        ),
    ]
