# Generated by Django 2.2.28 on 2022-08-15 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0040_normarelacionada_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normajuridica',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normajuridica_set', to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
    ]
