# Generated by Django 2.2.28 on 2022-09-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0042_norma_viewnormasestatisticas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewNormasEstatisticas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mais_acessadas', models.PositiveSmallIntegerField(verbose_name='Mais Acessadas')),
                ('ano_est', models.PositiveSmallIntegerField(verbose_name='Ano do Registro de Acesso')),
                ('mes_est', models.PositiveSmallIntegerField(verbose_name='Mês do Registro de Acesso')),
                ('norma_id', models.BigIntegerField(verbose_name='Id da Norma')),
                ('norma_count', models.PositiveSmallIntegerField(verbose_name='Mês do Registro de Acesso')),
                ('norma_numero', models.CharField(max_length=8, verbose_name='Número da Norma')),
                ('norma_ano', models.PositiveSmallIntegerField(verbose_name='Ano da Norma')),
                ('norma_ementa', models.TextField(verbose_name='Ementa')),
                ('norma_observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('norma_tipo_sigla', models.CharField(max_length=3, verbose_name='Sigla do Tipo da Norma')),
                ('norma_tipo_descricao', models.CharField(max_length=50, verbose_name='Descrição do Tipo da Norma')),
                ('norma_data', models.DateField(verbose_name='Data da Norma')),
            ],
            options={
                'db_table': 'norma_viewnormasestatisticas',
                'managed': False,
            },
        ),
    ]
