# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sapl.videoconf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoconferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=sapl.videoconf.models.gen_session_id, max_length=100, verbose_name='Chat ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, max_length=256, verbose_name='Descrição')),
                ('inicio', models.DateTimeField(auto_now=True, verbose_name='Data e Hora de Início')),
                ('termino', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Término')),
                ('finalizada', models.BooleanField(default=False, verbose_name='Finalizada?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Videoconferência',
                'verbose_name_plural': 'Videoconferências',
                'ordering': ['chat_id', 'descricao'],
            },
        ),
    ]
