# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parlamentares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoComissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Cargo')),
                ('unico', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Único')),
            ],
            options={
                'verbose_name': 'Cargo de Comissão',
                'verbose_name_plural': 'Cargos de Comissão',
            },
        ),
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
                ('data_extincao', models.DateField(blank=True, null=True, verbose_name='Data de Extinção')),
                ('apelido_temp', models.CharField(blank=True, max_length=100, verbose_name='Apelido')),
                ('data_instalacao_temp', models.DateField(blank=True, null=True, verbose_name='Data Instalação')),
                ('data_final_prevista_temp', models.DateField(blank=True, null=True, verbose_name='Data Prevista Término')),
                ('data_prorrogada_temp', models.DateField(blank=True, null=True, verbose_name='Novo Prazo')),
                ('data_fim_comissao', models.DateField(blank=True, null=True, verbose_name='Data Término')),
                ('secretario', models.CharField(blank=True, max_length=30, verbose_name='Secretário')),
                ('telefone_reuniao', models.CharField(blank=True, max_length=15, verbose_name='Tel. Sala Reunião')),
                ('endereco_secretaria', models.CharField(blank=True, max_length=100, verbose_name='Endereço Secretaria')),
                ('telefone_secretaria', models.CharField(blank=True, max_length=15, verbose_name='Tel. Secretaria')),
                ('fax_secretaria', models.CharField(blank=True, max_length=15, verbose_name='Fax Secretaria')),
                ('agenda_reuniao', models.CharField(blank=True, max_length=100, verbose_name='Data/Hora Reunião')),
                ('local_reuniao', models.CharField(blank=True, max_length=100, verbose_name='Local Reunião')),
                ('finalidade', models.TextField(blank=True, verbose_name='Finalidade')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-mail')),
                ('unidade_deliberativa', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Unidade Deliberativa')),
                ('ativa', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Comissão Ativa?')),
            ],
            options={
                'verbose_name': 'Comissão',
                'verbose_name_plural': 'Comissões',
            },
        ),
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.Comissao', verbose_name='Comissão')),
            ],
            options={
                'verbose_name': 'Composição de Comissão',
                'verbose_name_plural': 'Composições de Comissão',
            },
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Titular')),
                ('data_designacao', models.DateField(verbose_name='Data Designação')),
                ('data_desligamento', models.DateField(blank=True, null=True, verbose_name='Data Desligamento')),
                ('motivo_desligamento', models.CharField(blank=True, max_length=150, verbose_name='Motivo Desligamento')),
                ('observacao', models.CharField(blank=True, max_length=150, verbose_name='Observação')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.CargoComissao')),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacao_set', to='comissoes.Composicao')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar')),
            ],
            options={
                'verbose_name': 'Participação em Comissão',
                'verbose_name_plural': 'Participações em Comissão',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
            ],
            options={
                'verbose_name': 'Período de composição de Comissão',
                'verbose_name_plural': 'Períodos de composição de Comissão',
            },
        ),
        migrations.CreateModel(
            name='TipoComissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('natureza', models.CharField(choices=[('T', 'Temporária'), ('P', 'Permanente')], max_length=1, verbose_name='Natureza')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('dispositivo_regimental', models.CharField(blank=True, max_length=50, verbose_name='Dispositivo Regimental')),
            ],
            options={
                'verbose_name': 'Tipo de Comissão',
                'verbose_name_plural': 'Tipos de Comissão',
            },
        ),
        migrations.AddField(
            model_name='composicao',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.Periodo', verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='comissao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.TipoComissao', verbose_name='Tipo'),
        ),
    ]
