# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-09 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
