# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-09-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0002_auto_20170809_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='nome',
            field=models.CharField(max_length=160, verbose_name='Nome'),
        ),
    ]
