# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-02 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0003_auto_20171204_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.CargoComissao', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='composicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacao_set', to='comissoes.Composicao', verbose_name='Composição'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
    ]
