# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0004_auto_20160307_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='ativa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Comissão Ativa?'),
            preserve_default=False,
        ),
    ]
