# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-26 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0004_auto_20180102_1652'),
        ('comissoes', '0003_reuniao'),
    ]

    operations = [
    ]
