# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='url_audio',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='URL Arquivo Áudio (Formatos MP3 / AAC)'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='url_video',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'),
        ),
    ]
