# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0005_comissao_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='ativa',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Comissão Ativa?'),
        ),
    ]
