# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0006_auto_20160916_1243'),
        ('comissoes', '0006_auto_20160825_1335'),
    ]

    operations = [
    ]
