# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0008_auto_20160929_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='titular',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Titular'),
        ),
    ]
