# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0008_auto_20180227_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='local_reuniao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Local da Reunião'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='observacao',
            field=models.TextField(blank=True, max_length=150, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.TipoComissao', verbose_name='Tipo de Comissão'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='url_audio',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL do Arquivo de Áudio (Formatos MP3 / AAC)'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='url_video',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL do Arquivo de Vídeo (Formatos MP4 / FLV / WebM)'),
        ),
    ]
