# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0009_auto_20161011_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.TipoComissao', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.Periodo', verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comissoes.CargoComissao'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='composicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacao_set', to='comissoes.Composicao'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
    ]
