# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0009_auto_20180301_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome da Reunião'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='tema',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tema da Reunião'),
        ),
    ]
