# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-06 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0009_auto_20180301_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='hora_fim',
            field=models.TimeField(verbose_name='Horário de Término (hh:mm)'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Horário de Início (hh:mm)'),
        ),
    ]
