# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-09 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0010_auto_20180307_1645'),
        ('comissoes', '0010_auto_20180306_0918'),
    ]

    operations = [
    ]
