# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.comissoes.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0011_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAcessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data', models.DateField(blank=True, default=None, null=True, verbose_name='Data')),
                ('autor', models.CharField(blank=True, max_length=50, verbose_name='Autor')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('indexacao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=sapl.comissoes.models.anexo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentoacessorio_set', to='comissoes.Reuniao')),
            ],
            options={
                'verbose_name': 'Documento Acessório',
                'verbose_name_plural': 'Documentos Acessórios',
            },
        ),
    ]
