# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-12 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0012_documentoacessorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorio',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
    ]
