# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-05-03 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0013_auto_20180312_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composicao',
            options={'ordering': ['periodo'], 'verbose_name': 'Composição de Comissão', 'verbose_name_plural': 'Composições de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-data_inicio', '-data_fim'], 'verbose_name': 'Período de composição de Comissão', 'verbose_name_plural': 'Períodos de composição de Comissão'},
        ),
    ]
