# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0014_auto_20180503_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='hora_fim',
            field=models.TimeField(null=True, verbose_name='Horário de Término (hh:mm)'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='hora_inicio',
            field=models.TimeField(null=True, verbose_name='Horário de Início (hh:mm)'),
        ),
    ]
