# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0018_auto_20180924_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Término (hh:mm)'),
        ),
    ]
