# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0022_auto_20191120_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargocomissao',
            options={'ordering': ['id_ordenacao'], 'verbose_name': 'Cargo de Comissão', 'verbose_name_plural': 'Cargos de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='participacao',
            options={'ordering': ['-titular', 'cargo__id_ordenacao'], 'verbose_name': 'Participação em Comissão', 'verbose_name_plural': 'Participações em Comissão'},
        ),
        migrations.AddField(
            model_name='cargocomissao',
            name='id_ordenacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id de Ordenacao'),
        ),
    ]
