# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-31 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0022_presencareuniao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presencareuniao',
            options={'verbose_name': 'Presença em Reunião de Comissão', 'verbose_name_plural': 'Presenças em Reuniões de Comissão'},
        ),
    ]
