# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0022_auto_20191120_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocomissao',
            name='id_ordenacao',
            field=models.CharField(default='Não definido', max_length=50, verbose_name='Id de Ordenacao'),
        ),
    ]
