# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0023_cargocomissao_id_ordenacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargocomissao',
            options={'ordering': ['id_ordenacao'], 'verbose_name': 'Cargo de Comissão', 'verbose_name_plural': 'Cargos de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='participacao',
            options={'ordering': ['-titular', 'cargo__id_ordenacao'], 'verbose_name': 'Participação em Comissão', 'verbose_name_plural': 'Participações em Comissão'},
        ),
    ]
