# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0024_auto_20200602_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='comissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comissoes.Comissao', verbose_name='Comissão'),
        ),
    ]
