# Generated by Django 2.2.13 on 2020-10-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0025_auto_20200605_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoacessorio',
            options={'ordering': ('data', '-data_ultima_atualizacao'), 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'ordering': ('numero', 'comissao'), 'verbose_name': 'Reunião de Comissão', 'verbose_name_plural': 'Reuniões de Comissão'},
        ),
        migrations.AlterModelOptions(
            name='tipocomissao',
            options={'ordering': ('id',), 'verbose_name': 'Tipo de Comissão', 'verbose_name_plural': 'Tipos de Comissão'},
        ),
    ]
