# Generated by Django 2.2.28 on 2022-08-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0027_auto_20210209_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='motivo_desligamento',
            field=models.TextField(blank=True, verbose_name='Motivo Desligamento'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
