# Generated by Django 2.2.28 on 2023-10-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0029_auto_20221019_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargocomissao',
            name='unico',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Cargo Único'),
        ),
    ]
