# Generated by Django 2.2.28 on 2026-04-18 19:03

from django.db import migrations, models
import django.db.models.deletion
import sapl.base.fields
import sapl.comissoes.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_file_metadata'),
        ('comissoes', '0030_auto_20231007_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorio',
            name='arquivo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='upload_anexo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='upload_ata_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='reuniao',
            name='upload_pauta_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AlterField(
            model_name='documentoacessorio',
            name='arquivo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.comissoes.models.anexo_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Texto Integral'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='upload_anexo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.comissoes.models.anexo_upload_path, verbose_name='Anexo da Reunião'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='upload_ata',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.comissoes.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Reunião'),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='upload_pauta',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.comissoes.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Reunião'),
        ),
    ]
