# Generated by Django 2.2.28 on 2026-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissoes', '0030_auto_20231007_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data da Última Atualização'),
        ),
    ]
