# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0014_auto_20160223_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orador',
            name='url_discurso',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Vídeo'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='url_discurso',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Vídeo'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='url_audio',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Arquivo Áudio (Formatos MP3 / AAC)'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='url_video',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'),
        ),
    ]
