# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.utils
import sessao.models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0015_auto_20160307_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_ata',
            field=models.FileField(blank=True, null=True, upload_to=sessao.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_pauta',
            field=models.FileField(blank=True, null=True, upload_to=sessao.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Sessão'),
        ),
    ]
