# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0018_auto_20160510_0943'),
        ('sessao', '0016_auto_20160404_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome da Bancada, Bloco, Frente ou Grupo')),
                ('data_criacao', models.DateField(blank=True, verbose_name='Data Criação')),
                ('data_extincao', models.DateField(blank=True, verbose_name='Data Extinção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('legislatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Legislatura', verbose_name='Legislatura')),
                ('partido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name_plural': 'Bancadas',
                'verbose_name': 'Bancada',
            },
        ),
    ]
