# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0018_auto_20160517_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoBancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=80, verbose_name='Cargo de Bancada')),
                ('cargo_unico', models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Cargo Único')),
            ],
            options={
                'verbose_name_plural': 'Cargos de Bancada',
                'verbose_name': 'Cargo de Bancada',
            },
        ),
    ]
