# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0002_sessaoplenaria_interativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoOrdenacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro', models.CharField(max_length=30)),
                ('segundo', models.CharField(max_length=30)),
                ('terceiro', models.CharField(max_length=30)),
                ('quarto', models.CharField(max_length=30)),
                ('quinto', models.CharField(max_length=30)),
                ('sexto', models.CharField(max_length=30)),
                ('setimo', models.CharField(max_length=30)),
                ('oitavo', models.CharField(max_length=30)),
                ('nono', models.CharField(max_length=30)),
                ('decimo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Ordenação do Resumo de uma Sessão',
                'verbose_name_plural': 'Ordenação do Resumo de uma Sessão',
            },
        ),
    ]
