# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-01 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessao', '0004_votonominal_registro_votacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votonominal',
            name='registro_votacao',
        ),
        migrations.AddField(
            model_name='votoparlamentar',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Data/Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votoparlamentar',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='votoparlamentar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
