# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0007_auto_20170606_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votonominal',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='votonominal',
            name='parlamentar',
        ),
        migrations.RemoveField(
            model_name='votonominal',
            name='sessao',
        ),
        migrations.RemoveField(
            model_name='votonominal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votonominal',
            name='votacao',
        ),
        migrations.DeleteModel(
            name='VotoNominal',
        ),
    ]
