# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0008_auto_20170607_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votoparlamentar',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='IP'),
        ),
    ]
