# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-14 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0009_auto_20170619_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporesultadovotacao',
            name='natureza',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Rejeitado')], max_length=100, null=True, verbose_name='Natureza do Tipo'),
        ),
        migrations.AlterField(
            model_name='tiporesultadovotacao',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Tipo'),
        ),
    ]
