# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0010_auto_20170810_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='partidos',
            field=models.ManyToManyField(blank=True, to='parlamentares.Partido', verbose_name='Partidos'),
        ),
    ]
