# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0011_auto_20170814_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporesultadovotacao',
            name='natureza',
            field=models.CharField(blank=True, choices=[('A', 'Aprovado'), ('R', 'Rejeitado')], default='', max_length=100, verbose_name='Natureza do Tipo'),
            preserve_default=False,
        ),
    ]
