# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-15 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0012_auto_20170814_1615'),
        ('sessao', '0012_auto_20170815_1244'),
    ]

    operations = [
    ]
