# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0013_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoexpediente',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Expediente', 'verbose_name_plural': 'Tipos de Expediente'},
        ),
        migrations.AlterModelOptions(
            name='tiposessaoplenaria',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Sessão Plenária', 'verbose_name_plural': 'Tipos de Sessão Plenária'},
        ),
    ]
