# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0014_auto_20170905_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='painel_aberto',
            field=models.BooleanField(default=False, verbose_name='Painel está aberto?'),
        ),
    ]
