# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-31 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0015_sessaoplenaria_painel_aberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancada',
            name='data_criacao',
            field=models.DateField(null=True, verbose_name='Data Criação'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='data_criacao',
            field=models.DateField(null=True, verbose_name='Data Criação'),
        ),
    ]
