# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-03-27 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0017_auto_20180316_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrovotacao',
            name='data_hora_atualizacao',
        ),
        migrations.RemoveField(
            model_name='registrovotacao',
            name='data_hora_criacao',
        ),
    ]
