# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0018_auto_20180327_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporesultadovotacao',
            name='natureza',
            field=models.CharField(blank=True, choices=[('A', 'Aprovado'), ('R', 'Rejeitado')], max_length=1, verbose_name='Natureza do Tipo'),
        ),
    ]
