# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0019_auto_20180404_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemateria',
            name='registro_aberto',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Registro de Votação Iniciado?'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='registro_aberto',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Registro de Votação Iniciado?'),
        ),
    ]
