# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0019_cargobancada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargobancada',
            name='cargo_unico',
            field=models.CharField(choices=[(True, 'Sim'), (False, 'Não')], default=False, max_length=10, verbose_name='Cargo Único'),
        ),
    ]
