# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0038_auto_20160612_1506'),
        ('sessao', '0020_auto_20160517_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionaMultiplasMaterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa')),
            ],
            options={
                'verbose_name_plural': 'Tabela de Adicionar Várias Matérias',
                'verbose_name': 'Tabela de Adicionar Várias Matérias',
            },
        ),
    ]
