# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0021_adicionamultiplasmaterias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionamultiplasmaterias',
            name='materia',
        ),
        migrations.DeleteModel(
            name='AdicionaMultiplasMaterias',
        ),
    ]
