# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0022_auto_20160805_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancada',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome da Bancada, Bloco, ou Frente'),
        ),
    ]
