# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0023_auto_20180914_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaSessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True, verbose_name='Ocorrências da Sessão Plenária')),
                ('sessao_plenaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria')),
            ],
            options={
                'verbose_name_plural': 'Ocorrências da Sessão Plenaria',
                'verbose_name': 'Ocorrência da Sessão Plenaria',
            },
        ),
    ]
