# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0024_ocorrenciasessao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciasessao',
            name='sessao_plenaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
    ]
