# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0024_auto_20180926_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='justificativaausencia',
            options={'verbose_name': 'Justificativa de Ausência', 'verbose_name_plural': 'Justificativas de Ausências'},
        ),
        migrations.AddField(
            model_name='justificativaausencia',
            name='ausencia',
            field=models.PositiveIntegerField(choices=[(1, 'Sessão'), (2, 'Matéria')], default=1, verbose_name='Ausente em'),
        ),
    ]
