# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0025_auto_20160919_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientemateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Resultado'),
        ),
    ]
