# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-16 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0025_auto_20180919_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesessao',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='integrantemesa',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='presencaordemdia',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.ExpedienteMateria'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.OrdemDia'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='sessao_legislativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.SessaoLegislativa', verbose_name='Sessão Legislativa'),
        ),
        migrations.AlterField(
            model_name='sessaoplenariapresenca',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria'),
        ),
    ]
