# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0025_auto_20180927_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativaausencia',
            name='observacao',
            field=models.TextField(blank=True, max_length=150, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='justificativaausencia',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria', verbose_name='Sessão Plenárias'),
        ),
    ]
