# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0027_auto_20161003_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orador',
            name='url_discurso',
            field=models.CharField(blank=True, max_length=150, verbose_name='URL Vídeo ou Observação'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='url_discurso',
            field=models.CharField(blank=True, max_length=150, verbose_name='URL Vídeo ou Observação'),
        ),
    ]
