# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-24 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.sessao.models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0025_auto_20180924_1724'),
        ('sessao', '0027_auto_20181023_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativaAusencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.CharField(max_length=5, verbose_name='Horário (hh:mm)')),
                ('observacao', models.TextField(blank=True, max_length=150, verbose_name='Observação')),
                ('ausencia', models.PositiveIntegerField(choices=[(1, 'Matéria'), (2, 'Sessão')], default=1, verbose_name='Ausente em')),
                ('upload_anexo', models.FileField(blank=True, null=True, upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo de Justificativa')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar')),
                ('sessao_plenaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria', verbose_name='Sessão Plenária')),
            ],
            options={
                'verbose_name': 'Justificativa de Ausência',
                'verbose_name_plural': 'Justificativas de Ausências',
            },
        ),
        migrations.CreateModel(
            name='TipoJustificativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Justificativa',
                'verbose_name_plural': 'Tipos de Justificativa',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='justificativaausencia',
            name='tipo_ausencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.TipoJustificativa', verbose_name='Tipo de Justificativa'),
        ),
    ]
