# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0028_auto_20161004_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='orador',
            name='observacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='oradorexpediente',
            name='observacao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='url_discurso',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Vídeo'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='url_discurso',
            field=models.URLField(blank=True, max_length=150, verbose_name='URL Vídeo'),
        ),
    ]
