# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0029_auto_20161004_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancada',
            name='nome',
            field=models.CharField(max_length=80, verbose_name='Nome da Bancada'),
        ),
    ]
