# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0030_resumoordenacao_decimo_primeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_primeiro',
            field=models.CharField(default='Ocorrências da Sessão', max_length=30),
        ),
    ]
