# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0030_auto_20161216_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargobancada',
            name='cargo_unico',
            field=models.NullBooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Cargo Único ?'),
        ),
    ]
