# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0030_auto_20161216_1640'),
        ('sessao', '0030_auto_20161215_1652'),
    ]

    operations = [
    ]
