# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-28 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.sessao.models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0031_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo da Sessão'),
        ),
    ]
