# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-02 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0031_auto_20170102_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargobancada',
            name='cargo_unico',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Cargo Único ?'),
        ),
    ]
