# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0032_merge_20181122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumoordenacao',
            name='decimo_segundo',
            field=models.CharField(default='Votos Nominais Mat Expediente', max_length=30),
        ),
        migrations.AddField(
            model_name='resumoordenacao',
            name='decimo_terceiro',
            field=models.CharField(default='Votos Nominais Mat Ordem Dia', max_length=30),
        ),
    ]
