# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-10 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0032_sessaoplenaria_upload_anexo'),
        ('sessao', '0032_auto_20170102_0953'),
    ]

    operations = [
    ]
