# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sapl.sessao.models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0025_auto_20180924_1724'),
        ('sessao', '0033_auto_20190228_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='OradorOrdemDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.PositiveIntegerField(verbose_name='Ordem de pronunciamento')),
                ('url_discurso', models.URLField(blank=True, max_length=150, verbose_name='URL Vídeo')),
                ('observacao', models.CharField(blank=True, max_length=150, verbose_name='Observação')),
                ('upload_anexo', models.FileField(blank=True, null=True, upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar')),
                ('sessao_plenaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria')),
            ],
            options={
                'verbose_name_plural': 'Oradores da Ordem do Dia',
                'verbose_name': 'Orador da Ordem do Dia',
            },
        ),
    ]
