# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0034_oradorordemdia'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumoordenacao',
            name='decimo_quarto',
            field=models.CharField(default='Oradores da Ordem do Dia', max_length=30),
        ),
    ]
