# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0035_resumoordenacao_decimo_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientesessao',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientesessao_set', to='sessao.SessaoPlenaria'),
        ),
    ]
