# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0035_auto_20170213_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancada',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.AlterField(
            model_name='bancada',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Partido', verbose_name='Partido'),
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='expedientesessao',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='expedientesessao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.TipoExpediente'),
        ),
        migrations.AlterField(
            model_name='integrantemesa',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.CargoMesa'),
        ),
        migrations.AlterField(
            model_name='integrantemesa',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='integrantemesa',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar', verbose_name='Parlamentar'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa', verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='presencaordemdia',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='presencaordemdia',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sessao.ExpedienteMateria'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sessao.OrdemDia'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='tipo_resultado_votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.TipoResultadoVotacao', verbose_name='Resultado da Votação'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='legislatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Legislatura', verbose_name='Legislatura'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='sessao_legislativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.SessaoLegislativa', verbose_name='Sessão Legislativa'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.TipoSessaoPlenaria', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sessaoplenariapresenca',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='sessaoplenariapresenca',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='votonominal',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='votonominal',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='votonominal',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria'),
        ),
        migrations.AlterField(
            model_name='votonominal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votoparlamentar',
            name='parlamentar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar'),
        ),
        migrations.AlterField(
            model_name='votoparlamentar',
            name='votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.RegistroVotacao'),
        ),
    ]
