# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessao', '0036_auto_20190412_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotacao',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AddField(
            model_name='registrovotacao',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='registrovotacao',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
