# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0036_auto_20190412_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo',
            field=models.CharField(default='mat_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_primeiro',
            field=models.CharField(default='v_n_mat_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_quarto',
            field=models.CharField(default='ocorr_sessao', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_segundo',
            field=models.CharField(default='oradores_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_terceiro',
            field=models.CharField(default='oradores_expli', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='nono',
            field=models.CharField(default='lista_p_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='oitavo',
            field=models.CharField(default='oradores_exped', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='primeiro',
            field=models.CharField(default='id_basica', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='quarto',
            field=models.CharField(default='lista_p', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='quinto',
            field=models.CharField(default='exp', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='segundo',
            field=models.CharField(default='cont_mult', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='setimo',
            field=models.CharField(default='v_n_mat_exp', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='sexto',
            field=models.CharField(default='mat_exp', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='terceiro',
            field=models.CharField(default='mesa_d', max_length=50),
        ),
    ]
