# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0036_auto_20190410_0836'),
        ('sessao', '0036_auto_20190409_1452'),
    ]

    operations = [
    ]
