# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0037_auto_20190415_1635'),
        ('sessao', '0037_auto_20190415_1324'),
    ]

    operations = [
    ]
