# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0037_merge_20190411_1548'),
        ('sessao', '0036_auto_20190409_1334'),
    ]

    operations = [
    ]
