# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 14:30
from __future__ import unicode_literals

from django.db import migrations


def unifica_opcaoes_ordenacao_resumo(apps, schema_editor):
    ResumoOrdenacao = apps.get_model('sessao', 'ResumoOrdenacao')
    ro = ResumoOrdenacao.objects.get_or_create()[0]
    if 'oradores_o_d' not in ro.__dict__:
        ro.decimo_quarto = 'oradores_o_d'
        ro.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sessao', '0039_auto_20190430_0825'),
    ]

    operations = [
        migrations.RunPython(unifica_opcaoes_ordenacao_resumo)
    ]
