# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0040_auto_20190523_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='tema_solene',
            field=models.TextField(blank=True, max_length=500, verbose_name='Tema da Sessão Solene'),
        ),
    ]
