# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0041_auto_20190610_1300'),
        ('sessao', '0041_sessaoplenaria_tema_solene'),
    ]

    operations = [
    ]
