# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0042_merge_20190612_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificativaausencia',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo de Justificativa'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorordemdia',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_anexo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_ata',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_pauta',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Sessão'),
        ),
    ]
