# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0043_auto_20190712_1053'),
        ('sessao', '0043_auto_20190506_1452'),
    ]

    operations = [
    ]
