# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0044_merge_20190802_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoexpediente',
            options={'ordering': ['ordenacao'], 'verbose_name': 'Tipo de Expediente', 'verbose_name_plural': 'Tipos de Expediente'},
        ),
        migrations.AddField(
            model_name='tipoexpediente',
            name='ordenacao',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordenação'),
        ),
    ]
