# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materia', '0060_auto_20190930_1136'),
        ('sessao', '0045_auto_20190816_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLeitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('ip', models.CharField(blank=True, default='', max_length=30, verbose_name='IP')),
                ('data_hora', models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
            },
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='tipo_votacao',
            field=models.PositiveIntegerField(choices=[(1, 'Simbólica'), (2, 'Nominal'), (3, 'Secreta'), (4, 'Leitura')], default=1, verbose_name='Tipo de votação'),
        ),
        migrations.AlterField(
            model_name='justificativaausencia',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo de Justificativa'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorordemdia',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='tipo_votacao',
            field=models.PositiveIntegerField(choices=[(1, 'Simbólica'), (2, 'Nominal'), (3, 'Secreta'), (4, 'Leitura')], default=1, verbose_name='Tipo de votação'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='data_hora',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_ata',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_pauta',
            field=models.FileField(blank=True, max_length=200, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Sessão'),
        ),
        migrations.AlterField(
            model_name='votoparlamentar',
            name='data_hora',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.ExpedienteMateria'),
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materia.MateriaLegislativa'),
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='ordem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessao.OrdemDia'),
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
