# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0046_auto_20190827_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroleitura',
            name='data_hora',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='data_hora',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='votoparlamentar',
            name='data_hora',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data/Hora'),
        ),
    ]
