# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-09 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0047_auto_20190829_1253'),
        ('sessao', '0046_auto_20191001_1115'),
    ]

    operations = [
    ]
