# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-31 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0048_auto_20190829_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaoplenariapresenca',
            options={'verbose_name': 'Presença em Reunião de Comissão', 'verbose_name_plural': 'Presenças em Reuniões de Comissão'},
        ),
    ]
