# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0048_auto_20191029_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orador',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorordemdia',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
    ]
