# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-31 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0049_auto_20191031_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessaoplenariapresenca',
            options={'ordering': ['parlamentar__nome_parlamentar'], 'verbose_name': 'Presença em Sessão Plenária', 'verbose_name_plural': 'Presenças em Sessões Plenárias'},
        ),
    ]
