# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0048_auto_20190829_1253'),
        ('sessao', '0050_auto_20191029_1441'),
    ]

    operations = [
    ]
