# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0050_auto_20191029_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroleitura',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='registrovotacao',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='votoparlamentar',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
    ]
