# Generated by Django 2.2 on 2020-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0051_auto_20200416_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='painel_aberto',
            field=models.BooleanField(blank=True, default=False, verbose_name='Painel está aberto?'),
        ),
    ]
