# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0035_merge_20190802_0954'),
        ('painel', '0011_cronometro_last_stop_duration'),
        ('sessao', '0051_merge_20191209_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronometroLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cronometro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='painel.Cronometro')),
            ],
            options={
                'verbose_name': 'Tipo de Lista de Discurso - Cronômetro',
                'verbose_name_plural': 'Tipo de Listas de Discurso - Cronômetros',
                'ordering': ['tipo_lista', 'cronometro'],
            },
        ),
        migrations.CreateModel(
            name='ListaDiscurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orador_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar')),
                ('sessao_plenaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria', verbose_name='Sessão Plenária')),
            ],
            options={
                'verbose_name': 'Lista de Discurso',
                'verbose_name_plural': 'Listas de Discurso',
                'ordering': ['tipo', 'sessao_plenaria'],
            },
        ),
        migrations.CreateModel(
            name='ParlamentarLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenacao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordenação')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.ListaDiscurso')),
                ('parlamentar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parlamentares.Parlamentar')),
            ],
            options={
                'verbose_name': 'Lista de Discurso - Parlamentar',
                'verbose_name_plural': 'Listas de Discurso - Parlamentares',
                'ordering': ['lista', 'parlamentar', 'ordenacao'],
            },
        ),
        migrations.CreateModel(
            name='TipoListaDiscurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Lista de Discurso',
                'verbose_name_plural': 'Tipos de Lista de Discurso',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='listadiscurso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.TipoListaDiscurso', verbose_name='Tipo de Lista de Discurso'),
        ),
        migrations.AddField(
            model_name='cronometrolista',
            name='tipo_lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sessao.TipoListaDiscurso'),
        ),
        migrations.AlterUniqueTogether(
            name='parlamentarlista',
            unique_together=set([('lista', 'parlamentar')]),
        ),
        migrations.AlterUniqueTogether(
            name='listadiscurso',
            unique_together=set([('tipo', 'sessao_plenaria')]),
        ),
        migrations.AlterUniqueTogether(
            name='cronometrolista',
            unique_together=set([('tipo_lista', 'cronometro')]),
        ),
    ]
