# Generated by Django 2.2 on 2020-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0052_auto_20200521_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientemateria',
            name='registro_aberto',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Registro de Votação Iniciado?'),
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='votacao_aberta',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Votação iniciada?'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='registro_aberto',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Registro de Votação Iniciado?'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='votacao_aberta',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Votação iniciada?'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='finalizada',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Sessão finalizada?'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='iniciada',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=True, null=True, verbose_name='Sessão iniciada?'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='interativa',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Sessão interativa'),
        ),
    ]
