# Generated by Django 2.2.13 on 2020-09-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0054_popula_expedientepautasessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedientePautaSessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(blank=True, max_length=545)),
            ],
            options={
                'db_table': 'sessao_expedientepauta',
                'managed': False,
            },
        ),
    ]
