# Generated by Django 2.2.20 on 2021-08-05 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0055_auto_20210304_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsideracoesFinais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True, verbose_name='Considerações Finais da Sessão Plenária')),
                ('sessao_plenaria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sessao.SessaoPlenaria')),
            ],
            options={
                'verbose_name': 'Consideração Final da Sessão Plenária',
                'verbose_name_plural': 'Considerações Finais da Sessão Plenária',
                'ordering': ('id',),
            },
        ),
    ]
