# Generated by Django 2.2.24 on 2021-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0055_auto_20210304_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='status_cronometro',
            field=models.CharField(default='S', max_length=1, verbose_name='Status do cronômetro painel'),
        ),
    ]
