# Generated by Django 2.2.20 on 2021-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0056_ConsideracoesFinais'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumoordenacao',
            name='decimo_quinto',
            field=models.CharField(default='cons_finais', max_length=50),
        ),
    ]
