# Generated by Django 2.2.24 on 2021-10-22 00:36

from django.core.management import call_command
from django.db import migrations, models


def update_solr(*args, **kwargs):
    call_command('update_index', 'sessao', verbosity=3, batchsize=100)


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0058_corrige_data_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name='Data'),
        ),
        #migrations.RunPython(update_solr),

    ]
