# Generated by Django 2.2.24 on 2021-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0058_auto_20211006_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='status_cronometro_personalizado',
            field=models.CharField(default='S', max_length=1, verbose_name='Status do cronômetro personalizado'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='status_cronometro_aparte',
            field=models.CharField(default='S', max_length=1, verbose_name='Status do cronômetro aparte'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='status_cronometro_consideracoes_finais',
            field=models.CharField(default='S', max_length=1, verbose_name='Status do cronômetro consideracoes finais'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='status_cronometro_ordem_do_dia',
            field=models.CharField(default='S', max_length=1, verbose_name='Status do cronômetro ordem do dia'),
        ),
    ]
