# Generated by Django 2.2.24 on 2021-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0058_auto_20211006_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaoplenaria',
            name='status_cronometro',
        ),
        migrations.AddField(
            model_name='sessaoplenaria',
            name='status_cronometro_discurso',
            field=models.CharField(default='S', max_length=1, verbose_name='Status do cronômetro discurso'),
        ),
    ]
