# Generated by Django 2.2.24 on 2022-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0059_sessaoplenaria_data_ultima_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposessaoplenaria',
            name='tipo_numeracao',
            field=models.PositiveIntegerField(choices=[(1, 'Quinzenal'), (2, 'Mensal'), (5, 'Semestral'), (10, 'Anual'), (11, 'Sessão Legislativa'), (12, 'Legislatura'), (99, 'Numeração Única')], default=11, verbose_name='Tipo de Numeração'),
        ),
    ]
