# Generated by Django 2.2.28 on 2022-06-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0060_auto_20220321_0934'),
        ('sessao', '0062_auto_20220405_1307'),
    ]

    operations = [
    ]
