# Generated by Django 2.2.28 on 2022-07-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0081_auto_20220321_0934'),
        ('sessao', '0063_merge_20220609_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientemateria',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação Atual'),
        ),
        migrations.AddField(
            model_name='ordemdia',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação Atual'),
        ),
    ]
