# Generated by Django 2.2.28 on 2022-08-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0042_auto_20220805_1236'),
        ('sessao', '0064_auto_20220713_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('numero_ordem', models.PositiveIntegerField(verbose_name='Nº Ordem')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Recebida'), (2, 'Enviada')], default=1, verbose_name='Tipo da Correspondência')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.DocumentoAdministrativo', verbose_name='Documento Administrativo')),
                ('sessao_plenaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessao.SessaoPlenaria')),
            ],
            options={
                'verbose_name': 'Correspondência',
                'verbose_name_plural': 'Correspondências',
                'ordering': ('numero_ordem',),
            },
        ),
    ]
