# Generated by Django 2.2.28 on 2022-08-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0042_auto_20220805_1236'),
        ('sessao', '0065_correspondencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoplenaria',
            name='correspondencias',
            field=models.ManyToManyField(blank=True, related_name='sessoesplenarias', through='sessao.Correspondencia', to='protocoloadm.DocumentoAdministrativo'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_set', to='sessao.SessaoPlenaria'),
        ),
    ]
