# Generated by Django 2.2.28 on 2022-08-14 01:33

from django.db import migrations, models


def insere_correspondencia_antes_de_exp(apps, schema_editor):
    ResumoOrdenacao = apps.get_model('sessao', 'ResumoOrdenacao')
    ordenacao = ResumoOrdenacao.objects.get_or_create()[0]
    fields = list(map(lambda x: x.name, ResumoOrdenacao._meta.get_fields()))
    fields.reverse()

    for i, f in enumerate(fields):
        setattr(ordenacao, f, getattr(ordenacao, fields[i + 1]))

        if i + 2 == len(fields):
            return

        if getattr(ordenacao, f) == 'exp':
            setattr(ordenacao, fields[i + 1], 'correspondencia')
            ordenacao.save()
            return


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0066_auto_20220813_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumoordenacao',
            name='decimo_sexto',
            field=models.CharField(default='cons_finais', max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Recebida'), (2, 'Enviada'), (
                2, 'Interna')], default=1, verbose_name='Tipo da Correspondência'),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo',
            field=models.CharField(default='lista_p_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_primeiro',
            field=models.CharField(default='mat_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_quarto',
            field=models.CharField(default='oradores_expli', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_quinto',
            field=models.CharField(default='ocorr_sessao', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_segundo',
            field=models.CharField(default='v_n_mat_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='decimo_terceiro',
            field=models.CharField(default='oradores_o_d', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='nono',
            field=models.CharField(default='oradores_exped', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='oitavo',
            field=models.CharField(default='v_n_mat_exp', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='quinto',
            field=models.CharField(default='correspondencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='setimo',
            field=models.CharField(default='mat_exp', max_length=50),
        ),
        migrations.AlterField(
            model_name='resumoordenacao',
            name='sexto',
            field=models.CharField(default='exp', max_length=50),
        ),
        migrations.RunPython(insere_correspondencia_antes_de_exp)
    ]
