# Generated by Django 2.2.24 on 2022-08-16 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0067_auto_20220813_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Recebida'), (2, 'Enviada'), (3, 'Interna')], default=1, verbose_name='Tipo da Correspondência'),
        ),
        migrations.AlterField(
            model_name='expedientemateria',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação de Pauta'),
        ),
        migrations.AlterField(
            model_name='ordemdia',
            name='tramitacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.Tramitacao', verbose_name='Situação de Pauta'),
        ),
    ]
