# Generated by Django 2.2.28 on 2022-08-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0067_auto_20220813_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Recebida'), (2, 'Enviada'), (3, 'Interna')], default=1, verbose_name='Tipo da Correspondência'),
        ),
    ]
