# Generated by Django 2.2.28 on 2022-09-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0068_auto_20220816_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='sessao_plenaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondencia_set', to='sessao.SessaoPlenaria', verbose_name='Sessão Plenária'),
        ),
    ]
