# Generated by Django 2.2.28 on 2026-08-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0069_auto_20220919_1705'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='votoparlamentar',
            constraint=models.UniqueConstraint(condition=models.Q(ordem__isnull=False), fields=('parlamentar', 'ordem'), name='sessao_votoparlamentar_unique_parlamentar_ordem'),
        ),
        migrations.AddConstraint(
            model_name='votoparlamentar',
            constraint=models.UniqueConstraint(condition=models.Q(expediente__isnull=False), fields=('parlamentar', 'expediente'), name='sessao_votoparlamentar_unique_parlamentar_expediente'),
        ),
    ]
