# Generated by Django 2.2.28 on 2026-08-05 16:00

from django.db import migrations


# Mantém uma única presença por (sessão, parlamentar). Presença é um sim/não,
# então as linhas repetidas não carregam informação adicional: preserva-se a
# de menor id e descartam-se as demais.
REMOVE_DUPLICADAS_SQL = """
    DELETE FROM {tabela} a
    USING {tabela} b
    WHERE a.sessao_plenaria_id = b.sessao_plenaria_id
      AND a.parlamentar_id = b.parlamentar_id
      AND a.id > b.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0069_auto_20220919_1705'),
    ]

    operations = [
        migrations.RunSQL(
            REMOVE_DUPLICADAS_SQL.format(
                tabela='sessao_sessaoplenariapresenca'),
            migrations.RunSQL.noop),
        migrations.RunSQL(
            REMOVE_DUPLICADAS_SQL.format(tabela='sessao_presencaordemdia'),
            migrations.RunSQL.noop),
        migrations.AlterUniqueTogether(
            name='sessaoplenariapresenca',
            unique_together={('sessao_plenaria', 'parlamentar')},
        ),
        migrations.AlterUniqueTogether(
            name='presencaordemdia',
            unique_together={('sessao_plenaria', 'parlamentar')},
        ),
    ]
