# Generated by Django 2.2.28 on 2026-06-23 22:32

from django.db import migrations, models
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0069_auto_20220919_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_anexo',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Votações Nominais'),
        ),
    ]
