# Generated by Django 2.2.28 on 2026-04-18 19:03

from django.db import migrations, models
import django.db.models.deletion
import sapl.base.fields
import sapl.sessao.models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_file_metadata'),
        ('sessao', '0069_auto_20220919_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificativaausencia',
            name='upload_anexo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='orador',
            name='upload_anexo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='oradorexpediente',
            name='upload_anexo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='oradorordemdia',
            name='upload_anexo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='sessaoplenaria',
            name='upload_anexo_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='sessaoplenaria',
            name='upload_ata_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AddField(
            model_name='sessaoplenaria',
            name='upload_pauta_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.FileMetadata', verbose_name='File metadata'),
        ),
        migrations.AlterField(
            model_name='justificativaausencia',
            name='upload_anexo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo de Justificativa'),
        ),
        migrations.AlterField(
            model_name='orador',
            name='upload_anexo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorexpediente',
            name='upload_anexo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='oradorordemdia',
            name='upload_anexo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo do Orador'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_anexo',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.anexo_upload_path, verbose_name='Anexo da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_ata',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.ata_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Ata da Sessão'),
        ),
        migrations.AlterField(
            model_name='sessaoplenaria',
            name='upload_pauta',
            field=sapl.base.fields.MetadataFileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.sessao.models.pauta_upload_path, validators=[sapl.utils.restringe_tipos_de_arquivo_txt], verbose_name='Pauta da Sessão'),
        ),
    ]
