# Generated by Django 2.2.28 on 2026-08-16 17:36

from django.db import migrations, models


def remove_votos_duplicados(apps, schema_editor):
    """Preserva o voto canônico antes de criar os índices únicos."""
    VotoParlamentar = apps.get_model('sessao', 'VotoParlamentar')

    for materia_field in ('ordem_id', 'expediente_id'):
        grupos = {}
        votos = VotoParlamentar.objects.exclude(**{materia_field: None})
        for voto in votos.iterator():
            chave = (voto.parlamentar_id, getattr(voto, materia_field))
            grupos.setdefault(chave, []).append(voto)

        for votos_duplicados in grupos.values():
            if len(votos_duplicados) < 2:
                continue
            voto_preservado = max(
                votos_duplicados,
                key=lambda voto: (
                    voto.votacao_id is not None,
                    voto.data_hora is not None,
                    voto.data_hora,
                    voto.id,
                ))
            ids_removidos = [voto.id for voto in votos_duplicados
                             if voto.id != voto_preservado.id]
            VotoParlamentar.objects.filter(id__in=ids_removidos).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0069_auto_20220919_1705'),
    ]

    operations = [
        migrations.RunPython(
            remove_votos_duplicados, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='votoparlamentar',
            constraint=models.UniqueConstraint(condition=models.Q(ordem__isnull=False), fields=('parlamentar', 'ordem'), name='sessao_votoparlamentar_unique_parlamentar_ordem'),
        ),
        migrations.AddConstraint(
            model_name='votoparlamentar',
            constraint=models.UniqueConstraint(condition=models.Q(expediente__isnull=False), fields=('parlamentar', 'expediente'), name='sessao_votoparlamentar_unique_parlamentar_expediente'),
        ),
    ]
