# Generated by Django 2.2.28 on 2026-08-16 18:58

from django.db import migrations, models


def fecha_matérias_abertas_duplicadas(apps, schema_editor):
    """
    Pré-requisito para o AddConstraint abaixo: se já existir mais de uma
    OrdemDia/ExpedienteMateria com votacao_aberta=True (dado deixado por
    versões anteriores, que não garantiam essa invariante), a constraint
    falharia ao ser criada. Mantém aberta apenas a mais recentemente
    modificada de cada tabela e fecha as demais.
    """
    for model_name in ('OrdemDia', 'ExpedienteMateria'):
        model = apps.get_model('sessao', model_name)
        abertas = model.objects.filter(votacao_aberta=True).order_by('-id')
        for materia in abertas[1:]:
            materia.votacao_aberta = False
            materia.save(update_fields=['votacao_aberta'])


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0070_votoparlamentar_unique_constraint'),
    ]

    operations = [
        migrations.RunPython(
            fecha_matérias_abertas_duplicadas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='expedientemateria',
            constraint=models.UniqueConstraint(condition=models.Q(votacao_aberta=True), fields=('votacao_aberta',), name='sessao_expedientemateria_unique_votacao_aberta'),
        ),
        migrations.AddConstraint(
            model_name='ordemdia',
            constraint=models.UniqueConstraint(condition=models.Q(votacao_aberta=True), fields=('votacao_aberta',), name='sessao_ordemdia_unique_votacao_aberta'),
        ),
    ]
