# Generated by Django 2.2.28 on 2026-08-17 19:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessao', '0072_sessao_presencas_e_materias_votacoes_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoMateriasVotacoesView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_plenaria_id', models.IntegerField()),
                ('etapa_sessao', models.CharField(max_length=20)),
                ('numero_ordem', models.IntegerField()),
                ('materia_id', models.IntegerField()),
                ('materia_texto', models.TextField()),
                ('materia_ementa', models.TextField()),
                ('tipo_votacao', models.IntegerField()),
                ('tipo_votacao_descricao', models.CharField(max_length=20)),
                ('resultado_votacao', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('numero_votos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('votos_parlamentares', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('votacao_aberta', models.NullBooleanField()),
            ],
            options={
                'db_table': 'sessao_materias_votacoes_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoPresencasView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_plenaria_id', models.IntegerField()),
                ('etapa_sessao', models.CharField(max_length=20)),
                ('parlamentar_id', models.IntegerField()),
                ('nome_parlamentar', models.TextField()),
                ('filiacao', models.TextField()),
                ('ativo', models.BooleanField()),
            ],
            options={
                'db_table': 'sessao_presencas_view',
                'managed': False,
            },
        ),
    ]
