# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norma', '0013_auto_20160503_0926'),
        ('norma', '0013_auto_20160510_1404'),
    ]

    operations = [
    ]
