# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotextoarticulado',
            name='content_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Modelo Integrado'),
        ),
    ]
