# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0002_auto_20170825_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotextoarticulado',
            name='content_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='Modelo Integrado'),
        ),
        migrations.AlterField(
            model_name='tipotextoarticulado',
            name='participacao_social',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Participação Social'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipotextoarticulado',
            name='publicacao_func',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Histórico de Publicação'),
            preserve_default=False,
        ),
    ]
