# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-31 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0003_auto_20170825_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotextoarticulado',
            name='participacao_social',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Participação Social'),
        ),
        migrations.AlterField(
            model_name='tipotextoarticulado',
            name='publicacao_func',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Histórico de Publicação'),
        ),
    ]
