# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


def adjust_contagem_continua(apps, schema_editor):
    Dispositivo = apps.get_model('compilacao', 'Dispositivo')

    Dispositivo.objects.filter(
        tipo_dispositivo__contagem_continua=True
    ).update(contagem_continua=True)


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0005_auto_20180319_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='contagem_continua',
            field=models.BooleanField(choices=[(
                True, 'Sim'), (False, 'Não')], default=False, verbose_name='Contagem contínua'),
        ),
        migrations.AlterUniqueTogether(
            name='dispositivo',
            unique_together=set([('ta', 'ordem'), ('ta', 'dispositivo0', 'dispositivo1', 'dispositivo2', 'dispositivo3', 'dispositivo4', 'dispositivo5', 'tipo_dispositivo', 'contagem_continua', 'dispositivo_raiz', 'dispositivo_atualizador', 'ta_publicado',
                                                   'publicacao'), ('ta', 'dispositivo0', 'dispositivo1', 'dispositivo2', 'dispositivo3', 'dispositivo4', 'dispositivo5', 'tipo_dispositivo', 'dispositivo_raiz', 'dispositivo_pai', 'dispositivo_atualizador', 'ta_publicado', 'publicacao')]),
        ),
        migrations.RunPython(adjust_contagem_continua),
    ]
