# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0007_auto_20180911_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodispositivo',
            name='contagem_continua',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Contagem contínua'),
        ),
    ]
