# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-04 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0009_auto_20180926_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoarticulado',
            name='numero',
            field=models.CharField(max_length=8, verbose_name='Número'),
        ),
    ]
