# Generated by Django 2.2 on 2020-05-21 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0013_auto_20190924_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='dispositivo_atualizador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_alterados_set', to='compilacao.Dispositivo', verbose_name='Dispositivo Atualizador'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='dispositivo_pai',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos_filhos_set', to='compilacao.Dispositivo', verbose_name='Dispositivo Pai'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='dispositivo_raiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='compilacao.Dispositivo', verbose_name='Dispositivo Raiz'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='publicacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='compilacao.Publicacao', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivo_nota_set', to='compilacao.Dispositivo', verbose_name='Dispositivo da Nota'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Dono da Nota'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compilacao.TipoNota', verbose_name='Tipo da Nota'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compilacao.TextoArticulado', verbose_name='Texto Articulado'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='tipo_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compilacao.TipoPublicacao', verbose_name='Tipo de Publicação'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='veiculo_publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compilacao.VeiculoPublicacao', verbose_name='Veículo de Publicação'),
        ),
        migrations.AlterField(
            model_name='textoarticulado',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='textoarticulado',
            name='tipo_ta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='compilacao.TipoTextoArticulado', verbose_name='Tipo de Texto Articulado'),
        ),
        migrations.AlterField(
            model_name='tipodispositivorelationship',
            name='filho_permitido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='possiveis_pais', to='compilacao.TipoDispositivo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivorelationship',
            name='pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filhos_permitidos', to='compilacao.TipoDispositivo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivorelationship',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compilacao.PerfilEstruturalTextoArticulado'),
        ),
        migrations.AlterField(
            model_name='vide',
            name='dispositivo_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivo_base_set', to='compilacao.Dispositivo', verbose_name='Dispositivo Base'),
        ),
        migrations.AlterField(
            model_name='vide',
            name='dispositivo_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivo_citado_set', to='compilacao.Dispositivo', verbose_name='Dispositivo Referido'),
        ),
        migrations.AlterField(
            model_name='vide',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compilacao.TipoVide', verbose_name='Tipo do Vide'),
        ),
    ]
