# Generated by Django 2.2 on 2020-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0014_auto_20200521_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoarticulado',
            name='participacao_social',
            field=models.BooleanField(blank=True, choices=[(None, 'Padrão definido no Tipo'), (True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Participação Social'),
        ),
    ]
