# Generated by Django 2.2.13 on 2020-10-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0015_auto_20200609_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ('id',), 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='tiponota',
            options={'ordering': ('id',), 'verbose_name': 'Tipo de Nota', 'verbose_name_plural': 'Tipos de Nota'},
        ),
        migrations.AlterModelOptions(
            name='tipopublicacao',
            options={'ordering': ('id',), 'verbose_name': 'Tipo de Publicação', 'verbose_name_plural': 'Tipos de Publicação'},
        ),
        migrations.AlterModelOptions(
            name='tipotextoarticulado',
            options={'ordering': ('id',), 'verbose_name': 'Tipo de Texto Articulado', 'verbose_name_plural': 'Tipos de Texto Articulados'},
        ),
        migrations.AlterModelOptions(
            name='tipovide',
            options={'ordering': ('id',), 'verbose_name': 'Tipo de Vide', 'verbose_name_plural': 'Tipos de Vide'},
        ),
        migrations.AlterModelOptions(
            name='veiculopublicacao',
            options={'ordering': ('id',), 'verbose_name': 'Veículo de Publicação', 'verbose_name_plural': 'Veículos de Publicação'},
        ),
        migrations.AlterModelOptions(
            name='vide',
            options={'ordering': ('id',), 'verbose_name': 'Vide', 'verbose_name_plural': 'Vides'},
        ),
    ]
