# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0043_auto_20160110_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='url_externa',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Url externa'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='url_externa',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Link para Versão Eletrônica'),
        ),
    ]
