# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0045_auto_20160404_1411'),
        ('compilacao', '0048_auto_20160404_2309'),
    ]

    operations = [
    ]
