# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0053_auto_20160916_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo',
            unique_together=set([('ta', 'ordem'), ('ta', 'dispositivo0', 'dispositivo1', 'dispositivo2', 'dispositivo3', 'dispositivo4', 'dispositivo5', 'tipo_dispositivo', 'dispositivo_pai', 'dispositivo_atualizador', 'ta_publicado', 'publicacao')]),
        ),
    ]
