# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0056_auto_20161006_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='texto',
            field=models.TextField(blank=True, default='', verbose_name='Texto do Dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='texto_atualizador',
            field=models.TextField(blank=True, default='', verbose_name='Texto do Dispositivo no Dispositivo Atualizador'),
        ),
    ]
