# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0064_auto_20161104_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textoarticulado',
            old_name='visibilidade',
            new_name='privacidade'
        ),
    ]
