# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0068_auto_20161107_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textoarticulado',
            name='privacidade',
            field=models.IntegerField(choices=[(99, 'Privado'), (79, 'Imotável Restrito'), (69, 'Imutável Público'), (89, 'Em Edição'), (0, 'Público')], default=99, verbose_name='Privacidade'),
        ),
    ]
