# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilacao', '0071_tipotextoarticulado_perfis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodispositivo',
            name='nota_automatica_prefixo_html',
            field=models.TextField(blank=True, verbose_name='Prefixo html da nota automática'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='nota_automatica_sufixo_html',
            field=models.TextField(blank=True, verbose_name='Sufixo html da nota automática'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='rotulo_prefixo_html',
            field=models.TextField(blank=True, verbose_name='Prefixo html do rótulo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='rotulo_prefixo_texto',
            field=models.TextField(blank=True, verbose_name='Prefixo de Edição do rótulo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='rotulo_sufixo_html',
            field=models.TextField(blank=True, verbose_name='Sufixo html do rótulo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='rotulo_sufixo_texto',
            field=models.TextField(blank=True, verbose_name='Sufixo de Edição do rótulo'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='texto_prefixo_html',
            field=models.TextField(blank=True, verbose_name='Prefixo html do texto'),
        ),
        migrations.AlterField(
            model_name='tipodispositivo',
            name='texto_sufixo_html',
            field=models.TextField(blank=True, verbose_name='Sufixo html do texto'),
        ),
    ]
