# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LexmlProvedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provedor', models.PositiveIntegerField(verbose_name='Id do provedor')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do provedor')),
                ('sigla', models.CharField(max_length=15)),
                ('email_responsavel', models.EmailField(blank=True, max_length=50, verbose_name='E-mail do responsável')),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, verbose_name='Nome do responsável')),
                ('tipo', models.CharField(max_length=50)),
                ('id_responsavel', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id do responsável')),
                ('xml', models.TextField(blank=True, verbose_name='XML fornecido pela equipe do LexML:')),
            ],
            options={
                'verbose_name': 'Provedor Lexml',
                'verbose_name_plural': 'Provedores Lexml',
            },
        ),
        migrations.CreateModel(
            name='LexmlPublicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicador', models.PositiveIntegerField(verbose_name='Id do publicador')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do publicador')),
                ('email_responsavel', models.EmailField(blank=True, max_length=50, verbose_name='E-mail do responsável')),
                ('sigla', models.CharField(blank=True, max_length=255, verbose_name='Sigla do Publicador')),
                ('nome_responsavel', models.CharField(blank=True, max_length=255, verbose_name='Nome do responsável')),
                ('tipo', models.CharField(max_length=50)),
                ('id_responsavel', models.PositiveIntegerField(verbose_name='Id do responsável')),
            ],
            options={
                'verbose_name': 'Publicador Lexml',
                'verbose_name_plural': 'Publicadores Lexml',
            },
        ),
    ]
