# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexml', '0003_auto_20160216_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexmlprovedor',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail do responsável'),
        ),
        migrations.AlterField(
            model_name='lexmlpublicador',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=50, verbose_name='E-mail do responsável'),
        ),
    ]
