# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0025_auto_20160311_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='data_tramitacao',
            field=models.DateField(default=datetime.datetime(2016, 3, 21, 14, 13, 11, 96206, tzinfo=utc), verbose_name='Data Tramitação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='status',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 21, 14, 13, 17, 24259, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='materia.StatusTramitacao', verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='texto',
            field=models.TextField(verbose_name='Texto da Ação'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 21, 14, 13, 26, 344314, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_local',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 21, 14, 13, 27, 824247, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='+', to='materia.UnidadeTramitacao', verbose_name='Unidade Local'),
            preserve_default=False,
        ),
    ]
