# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0027_auto_20160404_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_destino', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
        ),
        migrations.AlterField(
            model_name='tramitacao',
            name='unidade_tramitacao_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes_origem', to='materia.UnidadeTramitacao', verbose_name='Unidade Local'),
        ),
    ]
