# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0028_auto_20160419_1056'),
        ('materia', '0028_auto_20160419_1000'),
    ]

    operations = [
    ]
