# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0029_auto_20160428_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numeracao',
            options={'ordering': ('materia', 'tipo_materia', 'numero_materia', 'ano_materia', 'data_materia'), 'verbose_name': 'Numeração', 'verbose_name_plural': 'Numerações'},
        ),
    ]
