# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0030_auto_20160429_1349'),
        ('materia', '0030_auto_20160502_1630'),
    ]

    operations = [
    ]
