# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0031_merge'),
        ('materia', '0031_auto_20160502_1131'),
    ]

    operations = [
    ]
