# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0031_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexada',
            name='materia_anexada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_anexada_set', to='materia.MateriaLegislativa'),
        ),
        migrations.AlterField(
            model_name='anexada',
            name='materia_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal_set', to='materia.MateriaLegislativa'),
        ),
    ]
