# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0032_auto_20160503_0926'),
        ('materia', '0035_auto_20160510_0949'),
    ]

    operations = [
    ]
