# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0012_parlamentar_unidade_deliberativa'),
        ('parlamentares', '0012_auto_20160307_0905'),
    ]

    operations = [
    ]
