# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0016_auto_20160404_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlamentar',
            name='unidade_deliberativa',
        ),
    ]
