# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0019_auto_20160518_1204'),
        ('parlamentares', '0020_auto_20160518_1201'),
    ]

    operations = [
    ]
