from django.urls import path

from .apps import AppConfig
from .views import (relatorio_capa_processo,
                    relatorio_documento_administrativo, relatorio_espelho,
                    relatorio_etiqueta_protocolo, relatorio_materia,
                    relatorio_ordem_dia, relatorio_protocolo, relatorio_sessao_plenaria,
                    resumo_ata_pdf, relatorio_sessao_plenaria_pdf, etiqueta_materia_legislativa,
                    relatorio_materia_tramitacao, RelatoriosListView, RelatorioMateriasPorAutorView,
                    RelatorioNormasPublicadasMesView, RelatorioNormasVigenciaView, RelatorioMateriasPorAnoAutorTipoView,
                    RelatorioMateriasTramitacaoView, RelatorioMateriaAnoAssuntoView, RelatorioHistoricoTramitacaoView,
                    RelatorioDataFimPrazoTramitacaoView, RelatorioPresencaSessaoView, RelatorioAtasView,
                    RelatorioReuniaoView, RelatorioAudienciaView, RelatorioHistoricoTramitacaoAdmView,
                    RelatorioDocumentosAcessoriosView, RelatorioNormasPorAutorView, RelatorioVotacoesNominaisView)
from ..base.views import EstatisticasAcessoNormas

app_name = AppConfig.name

urlpatterns = [
    path('relatorios/materia', relatorio_materia, name='relatorio_materia'),
    path('relatorios/capa-processo',
        relatorio_capa_processo, name='relatorio_capa_processo'),
    path('relatorios/ordem-dia', relatorio_ordem_dia,
        name='relatorio_ordem_dia'),
    path('relatorios/relatorio-documento-administrativo',
        relatorio_documento_administrativo,
        name='relatorio_documento_administrativo'),
    path('relatorios/espelho', relatorio_espelho,
        name='relatorio_espelho'),

    # Url utilizada no arquivo: templates/sessao/pauta_sessao_list.html
    path('relatorios/<int:pk>/sessao-plenaria',
        relatorio_sessao_plenaria, name='relatorio_sessao_plenaria'),

    path('relatorios/protocolo',
        relatorio_protocolo, name='relatorio_protocolo'),
    path('relatorios/<int:nro>/<int:ano>/etiqueta-protocolo',
        relatorio_etiqueta_protocolo, name='relatorio_etiqueta_protocolo'),

    # # Url utilizada no arquivo: templates/sessao/pauta_sessao_filter.html
    # url(r'^relatorios/pauta-sessao/(?P<pk>\d+)/$',
    #     relatorio_pauta_sessao, name='relatorio_pauta_sessao'),
    
    path('relatorios/<int:pk>/resumo_ata',
        resumo_ata_pdf, name='resumo_ata_pdf'),
    path('relatorios/<int:pk>/sessao-plenaria-pdf',
        relatorio_sessao_plenaria_pdf, name='relatorio_sessao_plenaria_pdf'),
    path('relatorios/<int:pk>/etiqueta-materia-legislativa',
        etiqueta_materia_legislativa, name='etiqueta_materia_legislativa'),

    path('relatorios/<int:pk>/materia-tramitacao',
        relatorio_materia_tramitacao, name='relatorio_materia_tramitacao'),

    # TODO mover estas telas para a app 'relatorios'
    path('sistema/relatorios/',
        RelatoriosListView.as_view(), name='relatorios_list'),
    path('sistema/relatorios/materia-por-autor',
        RelatorioMateriasPorAutorView.as_view(), name='materia_por_autor'),
    path('sistema/relatorios/relatorio-por-mes',
        RelatorioNormasPublicadasMesView.as_view(), name='normas_por_mes'),
    path('sistema/relatorios/relatorio-por-vigencia',
        RelatorioNormasVigenciaView.as_view(), name='normas_por_vigencia'),
    path('sistema/relatorios/estatisticas-acesso',
        EstatisticasAcessoNormas.as_view(), name='estatisticas_acesso'),
    path('sistema/relatorios/materia-por-ano-autor-tipo',
        RelatorioMateriasPorAnoAutorTipoView.as_view(),
        name='materia_por_ano_autor_tipo'),
    path('sistema/relatorios/materia-por-tramitacao',
        RelatorioMateriasTramitacaoView.as_view(),
        name='materia_por_tramitacao'),
    path('sistema/relatorios/materia-por-assunto',
        RelatorioMateriaAnoAssuntoView.as_view(),
        name='materia_por_ano_assunto'),
    path('sistema/relatorios/historico-tramitacoes',
        RelatorioHistoricoTramitacaoView.as_view(),
        name='historico_tramitacoes'),
    path('sistema/relatorios/data-fim-prazo-tramitacoes',
        RelatorioDataFimPrazoTramitacaoView.as_view(),
        name='data_fim_prazo_tramitacoes'),
    path('sistema/relatorios/presenca',
        RelatorioPresencaSessaoView.as_view(),
        name='presenca_sessao'),
    path('sistema/relatorios/atas',
        RelatorioAtasView.as_view(),
        name='atas'),
    path('sistema/relatorios/reuniao',
        RelatorioReuniaoView.as_view(),
        name='reuniao'),
    path('sistema/relatorios/audiencia',
        RelatorioAudienciaView.as_view(),
        name='audiencia'),
    path('sistema/relatorios/historico-tramitacoesadm',
        RelatorioHistoricoTramitacaoAdmView.as_view(),
        name='historico_tramitacoes_adm'),
    path('sistema/relatorios/documentos_acessorios',
        RelatorioDocumentosAcessoriosView.as_view(),
        name='relatorio_documentos_acessorios'),
    path('sistema/relatorios/votacoes_nominais',
        RelatorioVotacoesNominaisView.as_view(),
        name='relatorio_votacoes_nominais'),
    path('sistema/relatorios/normas-por-autor',
        RelatorioNormasPorAutorView.as_view(), name='normas_por_autor'),
]