from django.urls.conf import re_path

from .apps import AppConfig
from .views import (relatorio_capa_processo,
                    relatorio_documento_administrativo, relatorio_espelho,
                    relatorio_etiqueta_protocolo, relatorio_materia,
                    relatorio_ordem_dia, relatorio_protocolo, relatorio_sessao_plenaria,
                    resumo_ata_pdf, relatorio_sessao_plenaria_pdf, etiqueta_materia_legislativa,
                    relatorio_materia_tramitacao, RelatoriosListView, RelatorioMateriasPorAutorView,
                    RelatorioNormasPublicadasMesView, RelatorioNormasVigenciaView, RelatorioMateriasPorAnoAutorTipoView,
                    RelatorioMateriasTramitacaoView, RelatorioMateriaAnoAssuntoView, RelatorioHistoricoTramitacaoView,
                    RelatorioDataFimPrazoTramitacaoView, RelatorioPresencaSessaoView, RelatorioAtasView,
                    RelatorioReuniaoView, RelatorioAudienciaView, RelatorioHistoricoTramitacaoAdmView,
                    RelatorioDocumentosAcessoriosView, RelatorioNormasPorAutorView)
from ..base.views import EstatisticasAcessoNormas

app_name = AppConfig.name

urlpatterns = [
    re_path(r'^relatorios/materia$', relatorio_materia, name='relatorio_materia'),
    re_path(r'^relatorios/capa-processo$',
        relatorio_capa_processo, name='relatorio_capa_processo'),
    re_path(r'^relatorios/ordem-dia$', relatorio_ordem_dia,
        name='relatorio_ordem_dia'),
    re_path(r'^relatorios/relatorio-documento-administrativo$',
        relatorio_documento_administrativo,
        name='relatorio_documento_administrativo'),
    re_path(r'^relatorios/espelho$', relatorio_espelho,
        name='relatorio_espelho'),

    # Url utilizada no arquivo: templates/sessao/pauta_sessao_list.html
    re_path(r'^relatorios/(?P<pk>\d+)/sessao-plenaria$',
        relatorio_sessao_plenaria, name='relatorio_sessao_plenaria'),

    re_path(r'^relatorios/protocolo$',
        relatorio_protocolo, name='relatorio_protocolo'),
    re_path(r'^relatorios/(?P<nro>\d+)/(?P<ano>\d+)/etiqueta-protocolo$',
        relatorio_etiqueta_protocolo, name='relatorio_etiqueta_protocolo'),

    # # Url utilizada no arquivo: templates/sessao/pauta_sessao_filter.html
    # url(r'^relatorios/pauta-sessao/(?P<pk>\d+)/$',
    #     relatorio_pauta_sessao, name='relatorio_pauta_sessao'),

    re_path(r'^relatorios/(?P<pk>\d+)/resumo_ata$',
        resumo_ata_pdf, name='resumo_ata_pdf'),
    re_path(r'^relatorios/(?P<pk>\d+)/sessao-plenaria-pdf$',
        relatorio_sessao_plenaria_pdf, name='relatorio_sessao_plenaria_pdf'),
    re_path(r'^relatorios/(?P<pk>\d+)/etiqueta-materia-legislativa$',
        etiqueta_materia_legislativa, name='etiqueta_materia_legislativa'),

    re_path(r'^relatorios/(?P<pk>\d+)/materia-tramitacao$',
        relatorio_materia_tramitacao, name='relatorio_materia_tramitacao'),

    # TODO mover estas telas para a app 'relatorios'
    re_path(r'^sistema/relatorios/$',
        RelatoriosListView.as_view(), name='relatorios_list'),
    re_path(r'^sistema/relatorios/materia-por-autor$',
        RelatorioMateriasPorAutorView.as_view(), name='materia_por_autor'),
    re_path(r'^sistema/relatorios/relatorio-por-mes$',
        RelatorioNormasPublicadasMesView.as_view(), name='normas_por_mes'),
    re_path(r'^sistema/relatorios/relatorio-por-vigencia$',
        RelatorioNormasVigenciaView.as_view(), name='normas_por_vigencia'),
    re_path(r'^sistema/relatorios/estatisticas-acesso$',
        EstatisticasAcessoNormas.as_view(), name='estatisticas_acesso'),
    re_path(r'^sistema/relatorios/materia-por-ano-autor-tipo$',
        RelatorioMateriasPorAnoAutorTipoView.as_view(),
        name='materia_por_ano_autor_tipo'),
    re_path(r'^sistema/relatorios/materia-por-tramitacao$',
        RelatorioMateriasTramitacaoView.as_view(),
        name='materia_por_tramitacao'),
    re_path(r'^sistema/relatorios/materia-por-assunto$',
        RelatorioMateriaAnoAssuntoView.as_view(),
        name='materia_por_ano_assunto'),
    re_path(r'^sistema/relatorios/historico-tramitacoes$',
        RelatorioHistoricoTramitacaoView.as_view(),
        name='historico_tramitacoes'),
    re_path(r'^sistema/relatorios/data-fim-prazo-tramitacoes$',
        RelatorioDataFimPrazoTramitacaoView.as_view(),
        name='data_fim_prazo_tramitacoes'),
    re_path(r'^sistema/relatorios/presenca$',
        RelatorioPresencaSessaoView.as_view(),
        name='presenca_sessao'),
    re_path(r'^sistema/relatorios/atas$',
        RelatorioAtasView.as_view(),
        name='atas'),
    re_path(r'^sistema/relatorios/reuniao$',
        RelatorioReuniaoView.as_view(),
        name='reuniao'),
    re_path(r'^sistema/relatorios/audiencia$',
        RelatorioAudienciaView.as_view(),
        name='audiencia'),
    re_path(r'^sistema/relatorios/historico-tramitacoesadm$',
        RelatorioHistoricoTramitacaoAdmView.as_view(),
        name='historico_tramitacoes_adm'),
    re_path(r'^sistema/relatorios/documentos_acessorios$',
        RelatorioDocumentosAcessoriosView.as_view(),
        name='relatorio_documentos_acessorios'),
    re_path(r'^sistema/relatorios/normas-por-autor$',
        RelatorioNormasPorAutorView.as_view(), name='normas_por_autor'),
]