#!/bin/bash

# verifica antes se houve modificação em algum arquivo models.py
if git diff --cached --name-status | grep -q '^M.*models\.py$'; then
  # se a checagem de migrations falhar impedimos o commit
  set -e
  ./check_migrations.sh
fi
