#!/bin/bash

# aqui apenas reportamos, não impedimos o commit
./check_qa.sh
if [ $? -eq 1 ]
then
    RED='\033[0;31m'
    echo
    echo -e "${RED}#### POR FAVOR, CORRIJA OS PROBLEMAS APONTADOS!!! ####${NC}"
    echo
fi

# se os comandos a seguir falharem impedimos o commit
set -e
./check_migrations.sh
