# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-20 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoadministrativo',
            name='numero_protocolo',
        ),
    ]
