# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoInstituicao',
        ),
    ]
