# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0003_auto_20161009_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_tramitacoes_destino', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
        ),
    ]
