# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-04-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0003_auto_20180103_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='numero_externo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número Externo'),
        ),
    ]
