# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0004_documentoadministrativo_numero_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
