# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0004_auto_20161023_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocolo',
            options={'permissions': (('action_anular_protocolo', 'Permissão para Anular Protocolo'),), 'verbose_name': 'Protocolo', 'verbose_name_plural': 'Protocolos'},
        ),
    ]
