# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0005_auto_20180824_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='restrito',
            field=models.BooleanField(default=False, verbose_name='Acesso Restrito'),
        ),
    ]
