# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0005_auto_20161027_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='tipo_protocolo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tipo de Protocolo'),
        ),
    ]
