# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0006_documentoadministrativo_restrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='tramitacao',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Em Tramitação?'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
