# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0007_auto_20180924_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('hash', models.CharField(max_length=8)),
                ('confirmado', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocoloadm.DocumentoAdministrativo')),
            ],
            options={
                'verbose_name_plural': 'Acompanhamentos de Documento',
                'verbose_name': 'Acompanhamento de Documento',
            },
        ),
    ]
