# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0007_auto_20180924_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='interessado',
            field=models.CharField(blank=True, max_length=200, verbose_name='Interessado'),
        ),
    ]
