# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-16 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0007_auto_20161110_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumentoadministrativo',
            options={'ordering': ['descricao'], 'verbose_name': 'Tipo de Documento Administrativo', 'verbose_name_plural': 'Tipos de Documento Administrativo'},
        ),
    ]
