# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-10 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0008_acompanhamentodocumento'),
        ('protocoloadm', '0008_auto_20181009_1741'),
    ]

    operations = [
    ]
