# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-12 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='justificativa_anulacao',
            field=models.CharField(blank=True, max_length=260, verbose_name='Motivo'),
        ),
    ]
