# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0010_auto_20160309_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='justificativa_anulacao',
            field=models.CharField(blank=True, max_length=60, verbose_name='Motivo'),
        ),
    ]
