# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocoloadm.Protocolo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
