# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0012_auto_20170315_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
            preserve_default=False,
        ),
    ]
