# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-06 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0012_auto_20190104_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.TipoDocumentoAdministrativo', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='tipo_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.TipoMateriaLegislativa', verbose_name='Tipo de Matéria'),
        ),
    ]
