# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0013_auto_20170320_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocoloadm.Protocolo', verbose_name='Protocolo'),
        ),
    ]
