# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0013_auto_20190106_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='ip_data_hora_manual',
            field=models.CharField(blank=True, help_text='Endereço IP da estação de trabalho do usuário que está realizando Protocolo e informando data e hora manualmente.', max_length=15, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='user_data_hora_manual',
            field=models.CharField(blank=True, help_text='Usuário que está realizando Protocolo e informando data e hora manualmente.', max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(blank=True, help_text='Informado manualmente', null=True, verbose_name='Data do Protocolo'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='hora',
            field=models.TimeField(blank=True, help_text='Informado manualmente', null=True, verbose_name='Hora do Protocolo'),
        ),
    ]
