# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0011_auto_20190107_1407'),
        ('protocoloadm', '0013_auto_20190106_1336'),
    ]

    operations = [
    ]
