# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-25 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0014_auto_20170321_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorioadministrativo',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.DocumentoAdministrativo'),
        ),
        migrations.AlterField(
            model_name='documentoacessorioadministrativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.TipoDocumentoAdministrativo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Autor'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.Protocolo', verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.TipoDocumentoAdministrativo', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Autor'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.TipoDocumentoAdministrativo', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='tipo_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materia.TipoMateriaLegislativa', verbose_name='Tipo Matéria'),
        ),
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.DocumentoAdministrativo'),
        ),
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='protocoloadm.StatusTramitacaoAdministrativo', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='unidade_tramitacao_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adm_tramitacoes_destino', to='materia.UnidadeTramitacao', verbose_name='Unidade Destino'),
        ),
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='unidade_tramitacao_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adm_tramitacoes_origem', to='materia.UnidadeTramitacao', verbose_name='Unidade Local'),
        ),
    ]
