# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0015_auto_20190108_1606'),
        ('protocoloadm', '0016_auto_20190110_1345'),
    ]

    operations = [
    ]
