# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0016_auto_20190110_1345'),
        ('protocoloadm', '0011_auto_20190103_1446'),
    ]

    operations = [
    ]
