# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0017_merge_20190121_1552'),
        ('protocoloadm', '0018_auto_20190111_1804'),
    ]

    operations = [
    ]
