# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocoloadm', '0018_auto_20190314_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoadministrativo',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='tramitacaoadministrativo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
