# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0019_auto_20190429_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoadministrativo',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
