# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0020_tramitacaoadministrativo_timestamp'),
        ('protocoloadm', '0019_auto_20190426_0833'),
    ]

    operations = [
    ]
