# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0021_merge_20190429_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorioadministrativo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='texto_integral',
            field=models.FileField(blank=True, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Texto Integral'),
        ),
    ]
