# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0021_merge_20190429_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='ip_data_hora_manual',
            field=models.CharField(blank=True, help_text='Endereço IP da estação de trabalho do usuário que está realizando Protocolo e informando data e hora manualmente.', max_length=256, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='user_data_hora_manual',
            field=models.CharField(blank=True, help_text='Usuário que está realizando Protocolo e informando data e hora manualmente.', max_length=256, verbose_name='IP'),
        ),
    ]
