# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0021_merge_20190429_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='protocolo',
            unique_together=set([('numero', 'ano')]),
        ),
    ]
