# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0022_deduplica_protocolos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='protocolo',
            unique_together=set([('numero', 'ano')]),
        ),
    ]
