# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0023_merge_20190802_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitacaoadministrativo',
            name='ultima_edicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
    ]
