# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0023_auto_20190711_1755'),
        ('protocoloadm', '0023_merge_20190802_1112'),
    ]

    operations = [
    ]
