# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0024_tramitacaoadministrativo_ultima_edicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='ultima_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
    ]
