# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocoloadm', '0025_auto_20190815_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='ultima_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Edição'),
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
