# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0025_auto_20191001_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorioadministrativo',
            name='autor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Autor'),
        ),
    ]
