# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-03 18:19
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocoloadm', '0025_auto_20191001_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaProtocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), size=None)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
