# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-26 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0026_auto_20190815_1737'),
        ('protocoloadm', '0024_merge_20190821_1418'),
    ]

    operations = [
    ]
