# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import sapl.utils


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0026_auto_20191024_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoacessorioadministrativo',
            name='arquivo',
            field=models.FileField(blank=True, max_length=300, null=True, storage=sapl.utils.OverwriteStorage(), upload_to=sapl.utils.texto_upload_path, verbose_name='Arquivo'),
        ),
    ]
