# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-15 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0030_auto_20200114_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoadministrativo',
            name='complemento',
            field=models.CharField(blank=True, max_length=10, verbose_name='Complemento'),
        ),
    ]
