# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0031_documentoadministrativo_caractere_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='tramitacaoadministrativo',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='IP'),
        ),
    ]
