# Generated by Django 2.2 on 2020-05-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0032_auto_20200416_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='restrito',
            field=models.BooleanField(blank=True, default=False, verbose_name='Acesso Restrito'),
        ),
    ]
