# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0033_auto_20200521_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Autor'),
        ),
    ]
