# Generated by Django 2.2.13 on 2021-02-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0036_auto_20210107_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoacessorioadministrativo',
            options={'ordering': ('data', 'id'), 'verbose_name': 'Documento Acessório', 'verbose_name_plural': 'Documentos Acessórios'},
        ),
    ]
