# Generated by Django 2.2.13 on 2021-01-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0036_auto_20210103_1015'),
        ('protocoloadm', '0036_auto_20210107_1408'),
    ]

    operations = [
    ]
