# Generated by Django 2.2.24 on 2021-10-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocoloadm', '0037_auto_20210209_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='de_proposicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
