# Generated by Django 2.2.24 on 2021-10-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0038_protocolo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='data_envio',
            field=models.DateTimeField(null=True, verbose_name='Data de Envio'),
        ),
    ]
