# Generated by Django 2.2.24 on 2021-11-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0038_auto_20211025_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Autor', verbose_name='Autoria do Documento'),
        ),
    ]
