# Generated by Django 2.2.28 on 2022-08-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0081_auto_20220321_0934'),
        ('protocoloadm', '0040_auto_20220321_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoDocAdminMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anexacao', models.DateField(verbose_name='Data Anexação')),
                ('data_desanexacao', models.DateField(blank=True, null=True, verbose_name='Data Desanexação')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialegislativa_vinculada_set', to='protocoloadm.DocumentoAdministrativo', verbose_name='Documento Administrativo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentoadministrativo_vinculado_set', to='materia.MateriaLegislativa', verbose_name='Matéria Legislativa')),
            ],
            options={
                'verbose_name': 'Vinculo entre Documento Administrativo e Matéria Legislativa',
                'verbose_name_plural': 'Vinculos entre Documento Administrativo e Matéria Legislativa',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='documentoadministrativo',
            name='materiasvinculadas',
            field=models.ManyToManyField(blank=True, related_name='docadmsvinculados', through='protocoloadm.VinculoDocAdminMateria', to='materia.MateriaLegislativa'),
        ),
    ]
