# Generated by Django 2.2.28 on 2022-08-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0081_auto_20220321_0934'),
        ('protocoloadm', '0041_auto_20220804_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoadministrativo',
            name='materiasvinculadas',
            field=models.ManyToManyField(blank=True, related_name='docadmvinculados', through='protocoloadm.VinculoDocAdminMateria', to='materia.MateriaLegislativa'),
        ),
        migrations.AlterUniqueTogether(
            name='vinculodocadminmateria',
            unique_together={('documento', 'materia')},
        ),
    ]
