# Generated by Django 2.2.28 on 2022-09-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0042_auto_20220805_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoadministrativo',
            options={'ordering': ('ano', 'numero', 'id'), 'verbose_name': 'Documento Administrativo', 'verbose_name_plural': 'Documentos Administrativos'},
        ),
    ]
