# Generated by Django 2.2.28 on 2022-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocoloadm', '0043_auto_20220919_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoacessorioadministrativo',
            name='justificativa_restricao',
            field=models.TextField(blank=True, verbose_name='Justificativa de Restrição'),
        ),
        migrations.AddField(
            model_name='documentoacessorioadministrativo',
            name='restrito',
            field=models.BooleanField(blank=True, default=False, verbose_name='Restrito'),
        ),
    ]
